Remove content-ui
kyma-project/kyma pull request #10000
Opened 2020-11-23 09:11 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
[Original issue](https://github.com/kyma-project/console/issues/2056)

2020-11-23 10:25 UTC, Wawrzyn321 commented
/retest

2020-11-23 14:53 UTC, Wawrzyn321 commented
/test pre-master-kyma-gke-compass-integration

2020-11-23 16:07 UTC, Wawrzyn321 commented
/test pre-master-kyma-gke-compass-integration

2020-11-25 08:02 UTC, dariadomagala commented on components/console-backend-service/internal/domain/schema.resolvers.go
> +//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
can we remove it then? :)

2020-11-25 12:04 UTC, akucharska commented
/retest

2020-11-25 12:26 UTC, dariadomagala approved these changes

2020-11-27 10:00 UTC, kazydek submitted a review, later dismissed

2020-11-27 10:22 UTC, aerfio commented on resources/core/values.yaml
> -    clusterAssetGroupsVersion: master
This implies that there are changes needed to release process

2020-11-27 11:05 UTC, aerfio requested changes
Whoops, with those changes the website is not working, we need to investigate this

2020-11-27 14:50 UTC, Wawrzyn321 commented
/test pre-master-kyma-gke-compass-integration

2020-11-27 19:40 UTC, Wawrzyn321 commented
/test pre-master-kyma-gke-compass-integration

2020-11-30 09:48 UTC, Wawrzyn321 commented
/test pre-master-kyma-gke-compass-integration

2020-11-30 10:24 UTC, aerfio requested changes

2020-11-30 10:24 UTC, aerfio commented on resources/core/values.yaml
> +    enabled: false
right now it's `global.docs.enabled`, you have to either change this file or requirements.yaml in order to install kyma without those clusterassetgroups

2020-12-01 10:10 UTC, akucharska commented
/retest

2020-12-01 14:44 UTC, aerfio approved these changes

2020-12-01 15:01 UTC, akucharska approved these changes

2020-12-01 15:03 UTC, kazydek approved these changes

2020-12-01 15:21 UTC, pbochynski approved these changes

2020-12-02 06:00 UTC, dariadomagala approved these changes

2020-12-02 07:18 UTC, merged