Upgrade prometheus pushgateway charts to latest.
kyma-project/kyma pull request #10048
Opened 2020-11-25 15:26 UTC by rakesh-garimella

**Description**

Changes proposed in this pull request:

- Update prometheus pushgateway to latest upstream charts
- ...
- ...

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/9897

2020-11-30 08:39 UTC, rakesh-garimella commented
/retest

2020-11-30 10:22 UTC, rakesh-garimella commented
/retest

2020-12-02 09:00 UTC, suleymanakbas91 requested changes

2020-12-02 10:06 UTC, rakesh-garimella commented on resources/monitoring/charts/prometheus-pushgateway/Chart.yaml
> +appVersion: "1.3.0"
removed

2020-12-02 10:06 UTC, rakesh-garimella commented on resources/monitoring/charts/prometheus-pushgateway/templates/_helpers.tpl
> +
fixed

2020-12-02 12:25 UTC, suleymanakbas91 approved these changes

2020-12-02 13:12 UTC, merged