Upgrade kube-state-metrics chart
kyma-project/kyma pull request #10065
Opened 2020-11-27 09:37 UTC by skhalash

**Description**

Changes proposed in this pull request:

- Upgrade `kube-state-metrics` chart to the v2.9.4 of the upstream
- Make use of the custom `selectorLabels` template

**Related issue(s)**

2020-11-27 13:50 UTC, skhalash commented
/retest

2020-11-27 16:34 UTC, skhalash commented
/retest

2020-11-27 18:44 UTC, skhalash commented
/retest

2020-11-30 12:36 UTC, skhalash commented
/retest

2020-12-01 10:04 UTC, suleymanakbas91 requested changes

2020-12-01 10:04 UTC, suleymanakbas91 commented on resources/monitoring/charts/kube-state-metrics/Chart.yaml
> +appVersion: 1.9.7
Please delete `appVersion` field as discussed.

2020-12-01 13:39 UTC, skhalash commented on resources/monitoring/charts/kube-state-metrics/Chart.yaml
> +appVersion: 1.9.7
Done

2020-12-01 13:41 UTC, suleymanakbas91 approved these changes

2020-12-01 15:03 UTC, skhalash commented
/retest

2020-12-01 16:07 UTC, merged