Bump CBS - allow services without labels
kyma-project/kyma pull request #10228
Opened 2020-12-16 14:52 UTC by parostatkiem

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2020-12-17 10:10 UTC, Wawrzyn321 commented
/retest

2020-12-18 07:51 UTC, dariadomagala requested changes
please use master branch images

2020-12-18 08:00 UTC, Wawrzyn321 approved these changes

2020-12-18 11:42 UTC, dariadomagala approved these changes

2020-12-21 08:04 UTC, merged