Fix OpenSSL vulnerability for microfrontends
kyma-project/kyma pull request #10272
Opened 2020-12-31 13:37 UTC by parostatkiem

**Description**

Changes proposed in this pull request:

- use Alpine:3.12 as a base image
- ...
- ...

**Related issue(s)**

2020-12-31 13:45 UTC, Wawrzyn321 approved these changes

2021-01-04 08:36 UTC, parostatkiem commented
/retest

2021-01-04 08:59 UTC, dariadomagala approved these changes

2021-01-04 09:35 UTC, dariadomagala requested changes

2021-01-04 09:35 UTC, dariadomagala commented on resources/console/charts/web/values.yaml
> +    tag: "1d279dbf"
this image doesn't exist

2021-01-04 09:40 UTC, dariadomagala approved these changes

2021-01-04 09:42 UTC, dariadomagala requested changes
Changing my mind again 🙂 
add-ons are not updated

2021-01-05 08:16 UTC, dariadomagala approved these changes

2021-01-05 08:17 UTC, merged