Fast integration tests - service catalog checks
kyma-project/kyma pull request #10280
Opened 2021-01-04 14:42 UTC by pbochynski

**Description**

Changes proposed in this pull request:
- more checks for Service Catalog objects

2021-01-07 10:26 UTC, aerfio requested changes

2021-01-08 21:56 UTC, pbochynski commented on tests/fast-integration/test/getting-started-guides.js
> +    waitForK8sObject(watch, apiRulePath, {}, (_type, _apiObj, watchObj) => {
fixed

2021-01-08 21:56 UTC, pbochynski commented on tests/fast-integration/test/commerce-mock.js
> +    k8sDynamicApi.create(sbu);
fixed

2021-01-08 21:57 UTC, pbochynski commented on tests/fast-integration/test/commerce-mock.js
> +    k8sApply(k8sDynamicApi, [mocksNamespaceObj]);
fixed

2021-01-11 08:00 UTC, crabtree reviewed
Please see my comments

2021-01-11 10:02 UTC, crabtree approved these changes

2021-01-11 11:13 UTC, aerfio approved these changes

2021-01-11 11:19 UTC, crabtree commented
/retest

2021-01-11 11:22 UTC, crabtree commented
/test pre-kyma-artifacts

2021-01-11 11:23 UTC, pbochynski commented
/retest

2021-01-11 11:56 UTC, pbochynski commented
/retest

2021-01-11 15:30 UTC, pbochynski commented
/retest

2021-01-11 15:32 UTC, merged