Event Publisher NATS Helm Chart
kyma-project/kyma pull request #10375
Opened 2021-01-19 01:29 UTC by montaro

**Related issue(s)**
See also #9852

2021-01-19 01:29 UTC, montaro commented on resources/eventing/charts/event-publisher-nats/values.yaml
> +   natsPublishURL: nats.nats.svc.cluster.local
To be more parameterized

2021-01-19 14:06 UTC, montaro commented
/retest

2021-01-22 11:37 UTC, marcobebway commented on resources/eventing/charts/event-publisher-nats/templates/clusterrole.yaml
> +  labels: {{- include "event-publisher-nats.labels" . | nindent 4 }}
+1 for using `nindent`.

2021-01-25 14:50 UTC, marcobebway approved these changes

2021-01-26 10:46 UTC, marcobebway requested changes

2021-01-26 10:46 UTC, marcobebway commented on installation/resources/installer-cr-cluster.yaml.tpl
>        namespace: "istio-system"
Why do we need to change this file?

2021-01-26 12:28 UTC, montaro commented on installation/resources/installer-cr-cluster.yaml.tpl
>        namespace: "istio-system"
pushed by mistake, will revert

2021-01-26 15:51 UTC, marcobebway approved these changes

2021-01-28 22:49 UTC, merged