Document Kyma profiles
kyma-project/kyma pull request #10415
Opened 2021-01-21 14:37 UTC by klaudiagrz

**Description**

Since the work on [evaluation profile](https://github.com/kyma-project/kyma/issues/9673) is ongoing, we need to update the docs and describe both profiles available in Kyma.

We also need to update the already existing [installation docs](https://kyma-project.io/docs/#installation-overview) and already-existing docs related to profiles (see docs for [Logging](https://kyma-project.io/docs/components/logging#configuration-logging-production-profile) and [Service Mesh](https://kyma-project.io/docs/components/service-mesh#configuration-service-mesh-production-profile-production-profile) for reference). 

Changes proposed in this pull request:

- Add a generic document describing profiles available in Kyma
- Update installation and upgrade documents

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9902

2021-01-26 10:06 UTC, pbochynski requested changes

2021-02-11 09:37 UTC, kazydek approved these changes
LGTM 🎉

2021-02-11 09:52 UTC, kazydek approved these changes

2021-02-11 11:00 UTC, pbochynski approved these changes

2021-02-11 11:53 UTC, merged