Dynamic registry config
kyma-project/kyma pull request #10434
Opened 2021-01-25 13:08 UTC by tgorgol

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-01-28 13:16 UTC, aerfio requested changes

2021-01-28 13:16 UTC, aerfio commented on components/function-controller/internal/controllers/serverless/function_reconcile.go
> +	return DockerConfig{}, errors.New("Docker registry configuration not found")
add some more context here, maybe the names of needed secrets

2021-01-28 13:25 UTC, tgorgol commented on components/function-controller/internal/controllers/serverless/function_reconcile.go
> +		}, err
Good point, in this case `err` is never going to be `nil` so I'll just remove the `RequeueAfter`.

2021-01-28 13:36 UTC, aerfio approved these changes

2021-02-01 07:17 UTC, tgorgol commented
/retest

2021-02-01 10:38 UTC, m00g3n approved these changes

2021-02-01 10:40 UTC, merged