expose affinity
kyma-project/kyma pull request #10998
Opened 2021-03-26 15:19 UTC by kiranborrolla

**Description**

Changes proposed in this pull request:

expose affinity for ````cluster-essentials-pod-preset-webhook````
- adding podAntiAffinity rules for the components that we run with more than one replica

**Related issue(s)**

2021-03-26 15:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=10998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=10998) before we can accept your contribution.<br/><hr/>**kiran reddy borrolla** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=10998) it.</sub>

2021-03-26 17:43 UTC, lumi017 requested changes

2021-03-26 17:43 UTC, lumi017 commented on resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
> +        {{- end }}
Why did you add it?

2021-03-26 17:43 UTC, lumi017 commented on resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
> +        {{ toYaml .Values.affinity | indent 10 }}
bad indent

2021-04-15 14:02 UTC, lumi017 approved these changes

2021-05-26 08:14 UTC, werdes72 commented
@kiranborrolla Please sign CLA

2021-08-01 10:24 UTC, closed without merging