Remove node10 add node14 resources tests -resources, tests, cbs
kyma-project/kyma pull request #11121
Opened 2021-04-14 08:56 UTC by rJankowski93

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-04-15 09:24 UTC, rJankowski93 commented
/restest

2021-04-15 09:25 UTC, rJankowski93 commented
/retest

2021-04-15 09:48 UTC, rJankowski93 commented
/test pre-master-serverless-integration-k3s

2021-04-15 12:44 UTC, rJankowski93 commented
/test pre-kyma-components-function-runtimes

2021-04-15 13:11 UTC, rJankowski93 commented
/test pre-master-kyma-protecode-guard

2021-04-15 13:29 UTC, m00g3n approved these changes

2021-04-15 13:38 UTC, rJankowski93 commented
/restest

2021-04-15 17:29 UTC, rJankowski93 commented
/test pre-kyma-components-function-runtimes

2021-04-16 05:20 UTC, rJankowski93 commented
/retest

2021-04-16 06:43 UTC, tgorgol commented
/test pre-kyma-components-function-controller

2021-04-16 07:18 UTC, rJankowski93 commented
/retest

2021-04-16 10:11 UTC, Wawrzyn321 approved these changes

2021-04-16 10:54 UTC, kwiatekus requested changes

2021-04-16 10:54 UTC, kwiatekus commented on resources/cluster-essentials/files/functions.serverless.crd.yaml
> -              - nodejs10
Nodejs10 has to stay as allowed value in the status object. Otherwise editing existing function's runtime will fail.

2021-04-16 15:17 UTC, Wawrzyn321 approved these changes

2021-04-17 11:23 UTC, kwiatekus approved these changes

2021-04-20 15:02 UTC, pPrecel submitted a review, later dismissed

2021-04-22 05:53 UTC, crabtree approved these changes

2021-04-22 06:23 UTC, franpog859 submitted a review, later dismissed

2021-04-22 08:33 UTC, rJankowski93 commented
/retest

2021-04-22 10:09 UTC, franpog859 approved these changes

2021-04-22 11:32 UTC, piotrmiskiewicz approved these changes

2021-04-22 12:39 UTC, pPrecel approved these changes

2021-04-22 12:45 UTC, rakesh-garimella approved these changes

2021-04-22 17:18 UTC, Wawrzyn321 approved these changes

2021-04-23 08:08 UTC, strekm approved these changes
/meow

2021-04-23 08:08 UTC, merged