rafter,serverless: create Istio's vs instead of `apirule` during install
kyma-project/kyma pull request #11410
Opened 2021-06-02 00:48 UTC by piotrkpc

During uninstallation of Kyma race condition occurs and `ory-oathkeeper`
controller cannot remove it's finalizers if it will be delete
before it's resources. `rafter` and `serverless` components use
to relay on `apirule` during installation, but since they don't
use auth features so they could use Istio VirtualService instead
to avoid race conditions.

Resolves issue/10470

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-06-04 10:58 UTC, Tomasz-Smelcerz-SAP requested changes

2021-06-04 10:58 UTC, Tomasz-Smelcerz-SAP commented on resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
> +              number: 9000
```suggestion
              number: {{ .Values.service.port }}
```

2021-06-04 10:58 UTC, Tomasz-Smelcerz-SAP commented on resources/serverless/templates/virtualservice.yaml
> +              number: 5000
```suggestion
              number: {{ .Values.global.dockerServicePort }}
```

2021-06-04 10:58 UTC, Tomasz-Smelcerz-SAP commented on resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
> +      match:
Previously, an Oathkeeper rule was configured to only match `GET` requests on any path. Now we allow all methods. A `method` parameter should be added. See: https://istio.io/v1.9/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

2021-06-04 10:58 UTC, Tomasz-Smelcerz-SAP commented on resources/serverless/templates/virtualservice.yaml
> +      match:
Previously, an Oathkeeper rule was configured to only match `GET` and `HEAD` requests on any path. Now we allow all methods. A `method` parameter should be added and perhaps another HTTPMatchRequest object. See: https://istio.io/v1.9/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

2021-06-07 01:59 UTC, piotrkpc commented
/retest

2021-06-07 08:04 UTC, piotrkpc commented
hey, code owners, ptal:
@derberg @m00g3n @aerfio @pPrecel @magicmatatjahu 
thanks

2021-06-09 06:50 UTC, Tomasz-Smelcerz-SAP approved these changes

2021-06-09 06:50 UTC, Tomasz-Smelcerz-SAP commented
/meow

2021-06-09 07:08 UTC, piotrkpc commented
/retest

2021-06-09 07:48 UTC, merged