Update Istio chart to 1.10.0 version
kyma-project/kyma pull request #11434
Opened 2021-06-08 14:38 UTC by cnvergence

**Description**
For security & support reasons we should be up to date with the latest Istio release.
https://istio.io/latest/news/releases/1.10.x/announcing-1.10/change-notes/
https://istio.io/latest/news/releases/1.10.x/announcing-1.10/upgrade-notes/

Changes proposed in this pull request:

- Upgrade Istio to 1.10.0 version

**Related issue(s)**

Fixes #11423

2021-06-08 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=11434) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=11434) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=11434) it.</sub>

2021-06-12 09:08 UTC, cnvergence commented
/retest

2021-06-12 15:10 UTC, cnvergence commented
/retest

2021-06-14 07:04 UTC, cnvergence commented
/retest

2021-06-15 10:45 UTC, cnvergence commented
/test all

2021-06-15 12:48 UTC, cnvergence commented
/test all

2021-06-15 13:18 UTC, cnvergence commented
/test pre-main-kyma-gardener-azure-alpha-prod

2021-06-16 01:20 UTC, piotrkpc requested changes
I was reading some docs and if I understand this correctly, discovery selectors is the new selector work flow for injecting sidecar. I wonder if we can use it because the legacy selector logic will be removed.

https://docs.google.com/document/d/1umIDCxvTwfOBtNh-bbRb3eyOxJ_4jsSBXl4pfcAYqR0/edit?resourcekey=0-OOCyBAXemTcnpyDRjU48pQ#heading=h.xw1gqgyqs5b
https://istio.io/latest/blog/2021/discovery-selectors/

And if I understand all this correctly, after the upgrade and after we'll use new selector logic, docs below are no longer true.
https://github.com/kyma-project/kyma/blob/dbdd9427d86b262468b9ea3f254e0447dd6d479f/docs/service-mesh/03-03-sidecar-proxy-injection.md#L6-L13

2021-06-16 01:20 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster-evaluation.yaml
> +      useLegacySelectors: true
shouldn't we use https://istio.io/latest/blog/2021/discovery-selectors/#discovery-selectors-in-action instead?

2021-06-16 01:20 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster-production.yaml
> +      useLegacySelectors: true
shouldn't we use https://istio.io/latest/blog/2021/discovery-selectors/#discovery-selectors-in-action instead?

2021-06-16 01:20 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster.yaml
> +      useLegacySelectors: true
shouldn't we use https://istio.io/latest/blog/2021/discovery-selectors/#discovery-selectors-in-action instead?

2021-06-16 01:20 UTC, piotrkpc commented on resources/istio/files/istio-operator-minikube-evaluation.yaml
> +      useLegacySelectors: true
shouldn't we use https://istio.io/latest/blog/2021/discovery-selectors/#discovery-selectors-in-action instead?

2021-06-16 01:20 UTC, piotrkpc commented on resources/istio/files/istio-operator-minikube.yaml
> +      useLegacySelectors: true
shouldn't we use https://istio.io/latest/blog/2021/discovery-selectors/#discovery-selectors-in-action instead?

2021-06-16 07:17 UTC, piotrkpc commented on resources/istio/files/istio-operator-minikube.yaml
> +      useLegacySelectors: true
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:17 UTC, piotrkpc commented on resources/istio/files/istio-operator-minikube-evaluation.yaml
> +      useLegacySelectors: true
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:17 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster.yaml
> +      useLegacySelectors: true
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:17 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster-production.yaml
> +      useLegacySelectors: true
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:17 UTC, piotrkpc commented on resources/istio/files/istio-operator-cluster-evaluation.yaml
> +      useLegacySelectors: true
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:18 UTC, piotrkpc commented
during daily we have agreed to leave it for now and try to remove it in followup task.

2021-06-16 07:21 UTC, piotrkpc reviewed
during daily we have agreed to leave it for now and try to remove it in followup task. LGTM

2021-06-16 07:57 UTC, piotrkpc approved these changes
/lgtm

2021-06-16 07:57 UTC, werdes72 approved these changes
/meow

2021-06-16 09:26 UTC, merged