Add Recipe for using custom OIDC Idp
kyma-project/kyma pull request #11538
Opened 2021-06-23 14:28 UTC by kwiatekus

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/11521

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +You can combine user and group level permission in one binding. Run `kubectl create clusterrolebinding --help` in your terminal for more options.
```suggestion
You can combine user and group level permissions in one binding. Run `kubectl create clusterrolebinding --help` in your terminal for more options.
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +With this step you will set up the OIDC provider in  kubeconfig file to enforce authentication flow when accessing kyma via `kubectl`.
```suggestion
With this step, you will set up the OIDC provider in the kubeconfig file to enforce authentication flow when accessing Kyma using `kubectl`.
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +With this step you will set up the OIDC provider in  kubeconfig file to enforce authentication flow when accessing kyma via `kubectl`.
Rather "using" than "via -> https://kyma-project.io/community/guidelines/content/#style-and-terminology-style-and-terminology-terminology

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +1. Install [kubelogin](https://github.com/int128/kubelogin) plugin
```suggestion
1. Install the [kubelogin](https://github.com/int128/kubelogin) plugin.
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +2. Copy your current kubeconfig file into a new file
```suggestion
2. Copy your current kubeconfig file into a new file.
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +3. In the new kubeconfig file define a new `oidc` user and setup OIDC provider, as follows:
```suggestion
3. In the new kubeconfig file, define a new OIDC user and set up the OIDC provider. 
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +4. To enforce oidc login set the `oidc` user as a default user in the context
```suggestion
4. To enforce the OIDC login, set the OIDC user as a default user in the context.
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +        #- --oidc-client-secret=YOUR_CLIENT_SECRET this is not required if your OICS server supports PKCE authentication flow
```suggestion
        #- --oidc-client-secret=YOUR_CLIENT_SECRET this is not required if your OICS server supports the PKCE authentication flow
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +5. Now you can share the modified kubeconfig file to members of your team / organisation. When they will use it, your identity provider will do the authentication for you and the kubernetes api serve
```suggestion
5. Now you can share the modified kubeconfig file with the members of your team or organization. When they use it, your identity provider will handle the authentication. The Kubernetes API server will make sure they will have access to resources according to the role bound to them as individuals or group members.     
```

2021-06-24 08:40 UTC, kazydek commented on docs/03-tutorials/03-set-up-idp.md
> +        cluster: {your cluster name}
```suggestion
        cluster: {YOUR_CLUSTER_NAME}
```

2021-06-29 10:53 UTC, kwiatekus commented on docs/03-tutorials/03-set-up-idp.md
> +Now, whenever api server is called with a JWT token, the api server will be able to validate and extract the associated identity ( from the `username` and `group` claims of the JWT token).
Not really JWT token calling api server. I will rephrase.

2021-06-29 10:55 UTC, kwiatekus commented on docs/03-tutorials/03-set-up-idp.md
> +
done

2021-06-29 10:55 UTC, kwiatekus commented on docs/03-tutorials/03-set-up-idp.md
> +Now, whenever api server is called with a JWT token, the api server will be able to validate and extract the associated identity ( from the `username` and `group` claims of the JWT token).
done

2021-07-06 08:04 UTC, kwiatekus commented
/retest

2021-07-06 09:32 UTC, NHingerl requested changes

2021-07-06 09:32 UTC, NHingerl commented on docs/03-tutorials/03-set-up-idp.md
> +type: Tutorials
```suggestion
```

`type` metadata is not used any longer, right?

2021-07-06 09:32 UTC, NHingerl commented on docs/03-tutorials/03-set-up-idp.md
> +For example, if you want to use  k3d, you need to pass additional `--k3s-server-arg` flags containing the OIDC server configuration when creating the cluster. See the [specification](https://k3d.io/u
```suggestion
For example, if you want to use k3d, you need to pass additional `--k3s-server-arg` flags containing the OIDC server configuration when creating the cluster. See the [specification](https://k3d.io/usage/commands/k3d_cluster_create/) of the `k3d cluster create` command:
```

2021-07-06 11:25 UTC, NHingerl approved these changes

2021-07-06 11:25 UTC, merged