Move Central Application Gateway and Central Connectivity Validator to kyma-system namespace
kyma-project/kyma pull request #11631
Opened 2021-07-05 08:57 UTC by franpog859

**Description**

Changes proposed in this pull request:

- Move Central Application Gateway and Central Connectivity Validator to `kyma-system` namespace

**Related issue(s)**

See [the issue here](https://github.com/kyma-project/kyma/issues/11620)

2021-07-05 08:58 UTC, franpog859 commented
/test all

2021-07-05 09:16 UTC, franpog859 commented
/test all

2021-07-05 09:27 UTC, franpog859 commented
/test all

2021-07-05 09:45 UTC, franpog859 commented
/test all

2021-07-05 10:12 UTC, franpog859 commented
/test all

2021-07-06 07:24 UTC, franpog859 commented
/test all

2021-07-06 08:26 UTC, franpog859 commented
/test all

2021-07-06 08:56 UTC, franpog859 commented
Feel free to test it by yourself! To do it you can for example:
1. provision a cluster for example using Gardener
2. checkout on my branch, go to the `resources/application-connector/values.yaml` file, and change the `central_application_connectivity_validator.enabled` value to true, so there will be Central Application Connectivity Validator used:
  ```yaml
  central_application_connectivity_validator:
    enabled: &centralApplicationConnectivityValidatorEnabled true #change it from false to true
  ```
3. go to the fast-integration test directory with `cd tests/fast-integration` and install Kyma with Central Application Gateway using `./kyma.js install --skip-components kiali,tracing --with-central-application-gateway`
4. run the test with the Central Application Gateway flow using `env WITH_CENTRAL_APPLICATION_GATEWAY=true mocha test/2-commerce-mock.js -b`

2021-07-08 07:04 UTC, Maladie submitted a review, later dismissed

2021-07-08 08:12 UTC, mmitoraj requested changes
One small comment from me. Thanks!

2021-07-08 08:12 UTC, mmitoraj commented on components/central-application-gateway/README.md
> +- **applicationSecretsNamespace** is the Namespace in which the Application secrets used by Central Application Gateway exist. The default Namespace is `kyma-integration`.
```suggestion
- **applicationSecretsNamespace** is the Namespace in which the Application secrets used by the Central Application Gateway exist. The default Namespace is `kyma-integration`.
```

2021-07-08 10:20 UTC, franpog859 commented
/test all

2021-07-08 10:24 UTC, mmitoraj submitted a review, later dismissed

2021-07-08 10:25 UTC, Maladie submitted a review, later dismissed

2021-07-08 10:45 UTC, franpog859 commented
/test pre-main-kyma-gke-upgrade

2021-07-09 07:24 UTC, mmitoraj approved these changes

2021-07-09 07:43 UTC, Maladie approved these changes

2021-07-12 06:45 UTC, Maladie commented
/retest

2021-07-12 06:58 UTC, crabtree approved these changes

2021-07-12 12:14 UTC, ksputo approved these changes

2021-07-12 13:13 UTC, merged