Skr svcat install example resources
kyma-project/kyma pull request #11696
Opened 2021-07-15 21:23 UTC by voigt

**Description**

Changes proposed in this pull request:

- introduces new test for SKR - adding example resources

**Related issue(s)**
prow job: kyma-project/test-infra#3913
epic: https://github.tools.sap/kyma/backlog/issues/1656

2021-07-15 21:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=11696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=11696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=11696) it.</sub>

2021-07-29 11:14 UTC, wozniakjan commented on tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
> +async function installRessource(manifest, ressource, name, namespace) {
nit: consider `s/ressource/resource/`

2021-07-29 13:02 UTC, wozniakjan reviewed
few minor nits and comments below

2021-07-29 13:02 UTC, wozniakjan commented on tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
> +  console.log(`Finished deployment of Audit-Management in ${t1-t0} ms`)
this is pretty good idea, the testing framework does output elapsed time for each `It()` block that is over 5000ms.
```
  SKR SVCAT migration test
    ✓ Should provision SKR (1711998ms)
    ✓ Should save kubeconfig
    ✓ Should initialize K8s
    ✓ Should instantiate SM Instance and Binding (7749ms)
    ✓ Should install BTP Operator helm chart (22789ms)
    ✓ Should deprovision SKR (2371940ms)
    ✓ Should cleanup SM instances and bindings
```
But I like your approach and I agree we may want to have some more detailed and better consumable metrics to compose statistics than the default ms for slow `It()` blocks.

2021-07-29 15:03 UTC, voigt commented on tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
> +async function installRessource(manifest, ressource, name, namespace) {
Thanks, done!

2021-07-30 06:55 UTC, pbochynski requested changes
I would add your test case to the getting started guide test. I see you create the same types of resources (redis service instance, function, SBU, etc). 
You can save about 30-40 seconds required to build a function if you reuse getting started fixture.

2021-07-30 06:55 UTC, pbochynski commented on tests/fast-integration/utils/index.js
> +  const stat = {}
```suggestion
```

2021-07-30 06:55 UTC, pbochynski commented on tests/fast-integration/utils/index.js
> +  body.items.forEach(crd => stat[crd.spec.group] = stat[crd.spec.group] ? stat[crd.spec.group] + 1 : 1)
```suggestion
```

2021-07-30 06:55 UTC, pbochynski commented on tests/fast-integration/skr-svcat-migration-test/fixtures/02_serviceinstance_auditlog.yaml
> +  namespace: default
Remove namespace from yaml. You won't be able to install it in another namespace with current implementation of kubectlApply (namespace is applied only for resources where the namespace is not given).

2021-08-02 13:59 UTC, voigt commented
/test all

2021-08-02 15:26 UTC, voigt commented
/retest

2021-08-05 20:01 UTC, voigt commented on tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
> +    await deploy()
Added a destroy() job to remove resources before SKR shutdown.

2021-08-06 08:37 UTC, voigt commented
> I would add your test case to the getting started guide test. I see you create the same types of resources (redis service instance, function, SBU, etc).
> You can save about 30-40 seconds required to build a function if you reuse getting started fixture.

@pbochynski We will refactor this test once it is fully operational and prove that migration is working. This has been discussed with @PK85  as well.

2021-08-06 08:37 UTC, PK85 approved these changes

2021-08-06 08:42 UTC, pbochynski approved these changes
Conditional approval - please merge (remove) getting started guide with this test.

2021-08-06 08:43 UTC, merged