IstioOperator Helm chart for Kyma 2.0
kyma-project/kyma pull request #11702
Opened 2021-07-16 15:31 UTC by cnvergence

**Description**

Changes proposed in this pull request:

- Implement new istio chart containing minimal IstioOperator CR including only changes which kyma is introducing
- TBD support for profiles

**Related issue(s)**

Fixes #11636

2021-08-11 07:26 UTC, cnvergence commented
/retest

2021-08-16 12:26 UTC, mjakobczyk approved these changes

2021-08-16 12:28 UTC, cnvergence commented
/test pre-main-kyma-integration-k3d

2021-08-16 13:36 UTC, cnvergence commented
/test pre-main-kyma-gke-integration

2021-08-16 14:19 UTC, cnvergence commented
/test pre-main-kyma-gke-integration

2021-08-20 09:51 UTC, Tomasz-Smelcerz-SAP commented
/test pre-main-kyma-gke-integration

2021-08-23 08:37 UTC, pbochynski requested changes

2021-08-23 08:37 UTC, pbochynski commented on resources/istio-configuration/templates/tests/istio-kyma-validate.yaml
> +{{- if .Capabilities.APIVersions.Has "testing.kyma-project.io/v1alpha1" }}
Do we need this? `helm template` will not render it.

2021-08-23 08:37 UTC, pbochynski commented on resources/istio-configuration/templates/tests/istio-kyma-validate-rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Do we need it?

2021-08-23 08:52 UTC, pbochynski commented on resources/istio-configuration/values.yaml
> +test:
The test section can be removed.

2021-08-23 09:28 UTC, pbochynski approved these changes

2021-08-23 11:19 UTC, merged