Re-structure Service Mesh, Security and API Gateway docs
kyma-project/kyma pull request #11718
Opened 2021-07-20 13:48 UTC by mmitoraj

**Description**

The aim of the task was to re-structure the Service Mesh, Security, and API Gateway documents according to the Kyma 2.0 docs guidelines.

Changes proposed in this pull request:

- Renamed the file names according to the guidelines (adding the components' abbreviations)
- Changed the documents' order to match the new structure
- Removed the `type` metadata

2021-07-20 14:03 UTC, NHingerl requested changes

2021-07-20 14:05 UTC, NHingerl commented
Looking good! I basically only found stuff related to relative clauses.

For Troubleshooting topics, I'd personally suggest we have a structure with default headlines Symptom, Cause, Remedy. The [K2.0 content strategy](https://deploy-preview-565--kyma-project-community-preview.netlify.app/guidelines/content?utm_source=github&utm_campaign=bot_dp#content-strategy-k-2-0-content-strategy-k-2-0-troubleshooting-topics) is not agreed/merged yet but unless anyone objects, I'll keep proposing it :D

2021-07-21 06:51 UTC, mmitoraj commented on docs/04-operation-guides/security/sec-03-authorization-in-kyma.md
>  Kyma uses roles and user groups to manage access to the cluster. If you want to access the system through the Kyma Console or using kubectl, you must be authenticated with a JWT token. This token col
True! To be honest I didn't spend much time on the actual content. I will update it after reviewing all the docs together with Goats.

2021-07-21 06:54 UTC, mmitoraj commented on docs/04-operation-guides/troubleshooting/sec-03-console-not-enough-permissions.md
>  If you log in to the Kyma Console and receive `Not enough permissions` error message:
I will change that after reviewing the actual content together with Goats.  Thank you!

2021-07-21 07:29 UTC, NHingerl approved these changes

2021-07-21 07:30 UTC, merged