Adjusting Security documents for Kyma 2.0
kyma-project/kyma pull request #11747
Opened 2021-07-23 08:51 UTC by mmitoraj

**Description**

Changes proposed in this pull request:

- Update diagrams
- Remove outdated details
- Update all docs in accordance with Kyma 2.0 scope

**Related issue(s)** 
Resolves #10654, See also #11723

2021-08-02 08:54 UTC, mmitoraj commented
This is the list of documents to look at in the preview:

1. Tutorials -> Update TLS certificate
2. Operation guides -> Security -> Overview
3. Operation guides -> Security -> Authentication in Kyma
4. Operation guides -> Security -> Authorization in Kyma
5. Operation guides -> Security -> Access Kyma
6. Operation guides -> Security -> Ingress and Egress traffic
7. Operation guides -> Security -> OAuth2 server customization and operations
8. Operation guides -> Security -> Useful links
9. Operation guides -> Troubleshooting -> Issues with certificates on Gardener
10. Technical reference -> Configuration parameters -> Cluster users chart
11. Technical reference -> Configuration parameters -> ORY chart (not Security but API Exposure - WIP)

2021-08-03 11:21 UTC, werdes72 requested changes

2021-08-03 11:21 UTC, werdes72 commented on docs/04-operation-guides/security/07-sec-useful links.md
> +  - [Issues with certificates on Gardener](../troubleshooting/sec-02-certificates-gardener.md) come up.
This link is not working.

2021-08-03 11:21 UTC, werdes72 commented on docs/04-operation-guides/security/07-sec-useful links.md
> +  - [Issues with certificates on Gardener](../troubleshooting/sec-02-certificates-gardener.md) come up.
Seems like it should be:
`troubleshooting/sec-01-certificates-gardener`

2021-08-03 11:41 UTC, werdes72 approved these changes

2021-08-03 11:43 UTC, merged

2021-08-03 19:00 UTC, NHingerl commented on docs/04-operation-guides/security/02-sec-authentication-in-kyma.md
> +As Kyma is build on top of Istio Service Mesh, service-to-service authentication and encryption is enabled with [Istio MutualTLS](https://istio.io/latest/docs/concepts/security/#mutual-tls-authentica
... is built...

2021-08-03 19:00 UTC, NHingerl commented on docs/04-operation-guides/security/02-sec-authentication-in-kyma.md
> +Kyma uses a custom [API Gateway](../../01-overview/02-main-areas/api-exposure/apix-01-api-gateway.md) component that is build on top of [ORY Oathkeeper](https://www.ory.sh/oathkeeper/docs/). The API
... is built ...

2021-08-04 09:45 UTC, mmitoraj commented on docs/03-tutorials/sec-01-tls-certificates-security.md
> +    4. Add the newly generated certificate to the trusted certificates of your OS. For MacOS, run:
:(