Documentation for the back-channel communication
kyma-project/kyma pull request #11837
Opened 2021-08-03 15:40 UTC by pPrecel

**Description**

Changes proposed in this pull request:

- Add a new tutorial regarding back-channel communication.

**Related issue(s)**

https://github.com/kyma-project/cli/issues/824

2021-08-09 10:19 UTC, mmitoraj requested changes
Please see my comments below. Thank you.

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| setResponseHeader | key, value | Set a header to the response object based on the given `key` and the `value` |
```suggestion
| **setResponseHeader** | key, value | Sets a header to the response object based on the given key and the value |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| setResponseContentType | type | Set the `ContentType` header to the response object based on the given `type` |
```suggestion
| **setResponseContentType** | type | Sets the `ContentType` header to the response object based on the given type |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| setResponseStatus | status | Set the response statuc based on the given `status` |
```suggestion
| **setResponseStatus** | status | Sets the response status based on the given status |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| publishCloudEvent | event | Publish an CloudEvent to the publisher service based on the given CloudEvent object |
```suggestion
| **publishCloudEvent** | event | Publishes a CloudEvent on the publisher service based on the given CloudEvent object |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| buildResponseCloudEvent | id, type, data | Build an CloudEvent object based on the request CloudEvent object and given arguments |
```suggestion
| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and given arguments |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| Function | Arguments | Description |
```suggestion
| Function name | Arguments | Description |
```or "Method name" (depending on the answer to the question from one of the above comments.)

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| publishCloudEvent | event | Publish an CloudEvent to the publisher service based on the given CloudEvent object |
```suggestion
| **publishCloudEvent** | event | Publishes a CloudEvent on the publisher service based on the given CloudEvent object |
```

2021-08-09 10:19 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| buildResponseCloudEvent | id, type, data | Build an CloudEvent object based on the request CloudEvent object and given arguments |
```suggestion
| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and given arguments |
```

2021-08-16 09:40 UTC, pPrecel commented on docs/05-technical-reference/svls-08-function-specification.md
> +The `event` object is extended by methods making things easier. You can use every method by writing `event.Function_Name(Arguments...)`.
Definitely `ARGUMENTS`. The number of arguments is given in the `Arguments` section in the table and yup, my fault, the method is the same thing as the function. I will change it to the `function`

2021-08-16 10:46 UTC, kwiatekus submitted a review, later dismissed

2021-08-16 20:28 UTC, mmitoraj requested changes
Hi, I added a few more comments. Please make sure that the toggle displays correctly. Thank you.

2021-08-16 20:28 UTC, mmitoraj commented on docs/03-tutorials/eventing/evnt-01-setup-in-cluster-eventing.md
> +> **NOTE:** If you want to use a Function to publish a CloudEvent look at the [Event Object SDK specification](../../05-technical-reference/svls-08-function-specification.md).
```suggestion
> **NOTE:** If you want to use a Function to publish a CloudEvent, see the [Event object SDK specification](../../05-technical-reference/svls-08-function-specification.md#event-object-sdk).
```

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| **setResponseHeader** | key, value | Sets a header to the response object based on the given key and the value |
```suggestion
| **setResponseHeader** | key, value | Sets a header to the response object based on the given key and value |
```

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and given arguments |
```suggestion
| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and the given arguments |
```

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +```or "Method name" (depending on the answer to the question from one of the above comments.)
```suggestion

```
Remove the line and fix the toggle, please.

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| Function Name | Arguments | Description |
```suggestion
| Function name | Arguments | Description |
```

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and given arguments |
```suggestion
| **buildResponseCloudEvent** | id, type, data | Builds a CloudEvent object based on the request CloudEvent object and the given arguments |
```

2021-08-16 20:28 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
>  The `context` object contains information about the Function invocation, such as runtime details, execution timeout, or memory limits.
```suggestion
The `context` object contains information about the Function's invocation, such as runtime details, execution timeout, or memory limits.
```

2021-08-17 06:57 UTC, kwiatekus submitted a review, later dismissed

2021-08-17 13:44 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +The `event` object is extended by functions making some operations easier. You can use every function by providing `event.{FUNCTION_NAME(ARGUMENTS...)}`.
```suggestion
The `event` object is extended by Functions making some operations easier. You can use every Function by providing the following: `event.{FUNCTION_NAME(ARGUMENTS...)}`.
```
Is `event` an object or an argument? See the **Signature** section -> 

"Functions must accept two arguments that are passed to the Function handler:
- `event`
- `context`"

2021-08-18 07:09 UTC, mmitoraj commented on docs/05-technical-reference/svls-08-function-specification.md
> +| Function name | Arguments | Description |
```suggestion
| Method name | Arguments | Description |
```

2021-08-18 07:11 UTC, mmitoraj approved these changes

2021-08-18 07:25 UTC, merged