telemetry helm chart
kyma-project/kyma pull request #11901
Opened 2021-08-18 10:32 UTC by shorim

**Description**

Changes proposed in this pull request:

- add `telemetry` helm chart with 2 sub-charts: `operator` and `fluent-bit`

**Related issue(s)**

#11822

2021-08-18 12:40 UTC, shorim commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2021-08-18 12:40 UTC, shorim commented
/test pre-main-kyma-integration-k3d-central-app-connectivity

2021-08-19 12:27 UTC, JeremyHarisch submitted a review, later dismissed

2021-08-19 13:18 UTC, NHingerl requested changes

2021-08-19 13:18 UTC, NHingerl commented on resources/telemetry/charts/fluent-bit/README.md
> +[Fluent Bit](https://fluentbit.io) is a fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
```suggestion
[Fluent Bit](https://fluentbit.io) is a fast and lightweight log processor and forwarder for Linux, OSX, and BSD family operating systems.
```

2021-08-19 13:18 UTC, NHingerl commented on resources/telemetry/charts/fluent-bit/README.md
> +
are these instructions supposed to be done in order, or are they alternatives to each other?

2021-08-19 14:16 UTC, NHingerl submitted a review, later dismissed

2021-08-19 15:11 UTC, JeremyHarisch approved these changes

2021-08-19 15:17 UTC, NHingerl approved these changes

2021-08-19 15:59 UTC, shorim commented
/test pre-main-kyma-gke-upgrade

2021-08-20 07:37 UTC, lindnerby commented
/test pre-main-check-users-map

2021-08-20 09:58 UTC, majakurcius submitted a review, later dismissed
No changes suggested, as it's third-party READMEs.

2021-08-20 11:25 UTC, skhalash submitted a review, later dismissed

2021-08-20 12:51 UTC, elchead commented
/retest

2021-08-20 13:03 UTC, skhalash approved these changes

2021-08-20 13:12 UTC, majakurcius approved these changes

2021-08-20 13:26 UTC, JeremyHarisch approved these changes

2021-08-20 13:41 UTC, skhalash commented
/retest

2021-08-20 14:52 UTC, elchead commented
/retest

2021-08-20 16:13 UTC, merged