Troubleshooting guides update
kyma-project/kyma pull request #11991
Opened 2021-08-31 08:28 UTC by mmitoraj

**Description**

Changes proposed in this pull request:

- Rephrased some parts of the troubleshooting guides.

2021-08-31 09:06 UTC, Tomasz-Smelcerz-SAP commented on docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
> +After all the steps required to prepare your custom domain are finished, you receive the `connection refused` error when you try to expose a service. It shows up when you call the service endpoint by
In the "Remedy" section (I can't comment there) I would add:

In addion, ensure that your OS resolves the target host name to the same Ingress Gateway IP address.
run:
```
   host httpbin,kyma-goat.ga
```

2021-08-31 09:12 UTC, Tomasz-Smelcerz-SAP commented on docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
> +- Invalid DNS settings on your OS
In the "Remedy" section (I can't comment there):
- Add info that DNSEntry status should be: `Ready`
- Add a point: "Check if your local DNS configuration in /etc/hosts (or an equivalent file on your OS) contains an entry for the target host. Remove it."

2021-08-31 09:16 UTC, Tomasz-Smelcerz-SAP commented on docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
>  - VPN connection
- VPN connection (issues related to DNS servers managed by VPN provider)

2021-08-31 09:22 UTC, Tomasz-Smelcerz-SAP commented on docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
> +After all the steps required to prepare your custom domain are finished, you receive the `connection refused` error when you try to expose a service. It shows up when you call the service endpoint by
`connection refused` or `connection timeout`

2021-08-31 12:12 UTC, Tomasz-Smelcerz-SAP submitted a review, later dismissed

2021-08-31 12:44 UTC, klaudiagrz commented on docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
> +After all the steps required to prepare your custom domain are finished, you receive the `connection refused` or `connection timeout` error when you try to expose a service. It shows up when you call
Please add the link to the tutorial on how to prepare your custom domain.

2021-08-31 12:44 UTC, klaudiagrz commented on docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
> +After all the steps required to prepare your custom domain are finished, you receive the `could not resolve host` error when you try to expose a service. It shows up when you call the service endpoin
Please add the link to the tutorial on how to prepare your custom domain.

2021-08-31 12:44 UTC, klaudiagrz commented on docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
> +host httpbin.kyma-goat.ga
As discussed, please make it more generic.

2021-08-31 12:44 UTC, klaudiagrz commented on docs/04-operation-guides/troubleshooting/apix-04-dns-mgt-resource-ignored.md
> +If you have a non-Gardener cluster, the DNSProvider or DNSEntry CR you created are ignored by the controller.
```suggestion
If you have a non-Gardener cluster, the DNS Provider or DNS Entry CR you created are ignored by the controller.
```

2021-08-31 12:44 UTC, klaudiagrz commented on docs/04-operation-guides/troubleshooting/apix-04-dns-mgt-resource-ignored.md
> +If you have a non-Gardener cluster, the DNSProvider or DNSEntry CR you created are ignored by the controller.
^ You write it with space in other docs. Whatever option you decide on, please make it consistent in all the docs.

2021-09-01 11:37 UTC, klaudiagrz approved these changes

2021-09-01 11:38 UTC, klaudiagrz requested changes
Please revert the last commit

2021-09-02 06:57 UTC, klaudiagrz approved these changes

2021-09-02 06:57 UTC, merged