Update the doc for kyma.2.0
kyma-project/kyma pull request #12105
Opened 2021-09-15 10:11 UTC by mmitoraj

**Description**

Changes proposed in this pull request:

- Update links
- Update diagrams
- Update content
- Update structure

**Related issue(s)**
Resolves #11746

2021-09-16 07:22 UTC, mmitoraj commented
API EXPOSURE
1. Overview -> Main areas -> API Exposure
2. Overview -> Main areas -> API Exposure -> API Gateway
3. Overview -> Main areas -> API Exposure -> Useful links
4. Tutorials -> API Exposure -> Expose a service
5. Tutorials -> API Exposure -> Expose and secure a service
6. Tutorials -> API Exposure -> Use a custom domain to expose service
7. Operation guides -> Troubleshooting -> Cannot connect to a service exposed by an APIRule
8. Operation guides -> Troubleshooting -> External DNS management - connection refused or timeout
9. Operation guides -> Troubleshooting -> External DNS management - could not resolve host
10. Operation guides -> Troubleshooting -> External DNS management - resource ignored by the controller
11. Operation guides -> Troubleshooting -> Certificate management - Issuer not created
12. Technical reference -> Allowed domains in the API Gateway Controller
13. Technical reference -> Blocked services in the API Gateway Controller
14. Technical reference -> Configuration parameters -> ORY chart
15. Technical reference -> Custom resources -> APIRule
16. Technical reference -> Configuration parameters -> Istio chart

2021-09-16 12:41 UTC, strekm submitted a review, later dismissed
/meow

2021-09-16 14:14 UTC, NHingerl requested changes

2021-09-16 14:14 UTC, NHingerl commented on docs/05-technical-reference/apix-02-whitelisted-domains.md
> +>**TIP:** For more information, read about the [Api CR statuses](./00-custom-resources/apix-01-apirule.md#status-codes).
```suggestion
>**TIP:** For more information, read about the [API CR statuses](./00-custom-resources/apix-01-apirule.md#status-codes).
```

2021-09-16 14:14 UTC, NHingerl commented on docs/05-technical-reference/apix-03-blacklisted-services.md
> +>**TIP:** For more information, read about the [Api CR statuses](./00-custom-resources/apix-01-apirule.md#status-codes).
```suggestion
>**TIP:** For more information, read about the [API CR statuses](./00-custom-resources/apix-01-apirule.md#status-codes).
```

2021-09-16 14:14 UTC, NHingerl commented on docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
> +  - The [ORY chart](../../../05-technical-reference/05-configuration-parameters/apix-02-ory-chart.md)
```suggestion
  - The [ORY chart](../../../05-technical-reference/00-configuration-parameters/apix-02-ory-chart.md)
```
link was broken

2021-09-17 07:58 UTC, mmitoraj commented
Invalid commits after solving a merge conflict.

2021-09-17 07:58 UTC, closed without merging