[istio-conf] adjust helm settings to match Kyma 1 convention for tracing
kyma-project/kyma pull request #12524
Opened 2021-11-03 07:29 UTC by piotrkpc

In Kyma2 tracing was controlled by setting `meshConfig.enableTracing` while
in Kyma 1.x it's `global.tracing.enabled`. This changes the config, so it matches
Kyma 1.x convention

Resolves TODO:

2021-11-03 08:08 UTC, piotrkpc commented
/retest

2021-11-03 14:24 UTC, strekm requested changes
i would like to see support for both properties:
- `global.tracing.enabled`
- `meshConfig.enableTracing`

i see it we have both in values.yaml but in istio-operator.yaml no usage of `global.tracing.enabled` at all. have a look how to use templating in values.yaml

2021-11-03 17:49 UTC, piotrkpc commented
> i would like to see support for both properties:
> 
> * `global.tracing.enabled`
> * `meshConfig.enableTracing`
> 
> i see it we have both in values.yaml but in istio-operator.yaml no usage of `global.tracing.enabled` at all. have a look how to use templates in values.yaml

Please correct me if I'm wrong but I cannot use templates in `values.yaml`. References [0], [1]
[0]: https://github.com/helm/helm/issues/2492#issuecomment-304110843
[1]: https://github.com/helm/helm/issues/2133#issuecomment-287451865

2021-11-04 10:32 UTC, closed without merging

2021-11-04 10:35 UTC, piotrkpc commented
closed in favor of https://github.com/kyma-project/kyma/pull/12539 because I used wrong branch