Add a caution note
kyma-project/kyma pull request #12546
Opened 2021-11-05 11:22 UTC by mmitoraj

**Description**

Changes proposed in this pull request:

- Added Kubernetes as Kyma installation prerequisite
- Added a caution note about deprecating Docker in Kubernetes

2021-11-05 12:30 UTC, janmedrek submitted a review, later dismissed

2021-11-08 09:31 UTC, kwiatekus submitted a review, later dismissed

2021-11-08 10:37 UTC, klaudiagrz commented
Resolves this issue:
#12558

2021-11-08 11:02 UTC, pbochynski requested changes

2021-11-08 11:02 UTC, pbochynski commented on docs/02-get-started/README.md
> +- [Kubernetes](https://kubernetes.io/docs/setup/) (v1.19 or greater)
Kyma doesn't work on Kubernetes 1.22
We need be more specific:  v1.19 - v1.21

2021-11-08 21:08 UTC, mmitoraj commented
PR blocked: installation of the Serverless component on AKS with k8s version 1.20.9 failed

2021-11-15 08:15 UTC, mmitoraj reviewed
The installation worked

2021-11-15 08:18 UTC, pbochynski submitted a review, later dismissed

2021-11-15 13:33 UTC, majakurcius commented on docs/04-operation-guides/operations/02-install-kyma.md
> +  - [k3d](https://k3d.io) (for the local installation only)
```suggestion
  - [k3d](https://k3d.io) (for local installation only)
```
The process, not the instance.

2021-11-15 13:34 UTC, majakurcius commented on docs/02-get-started/README.md
> +- [k3d](https://k3d.io) (v4.0.0 or higher with [Kubernetes](https://kubernetes.io/docs/setup/) v1.19 - recommended, 1.20, or 1.21)
Thank you for changing it to `higher`! 😻

2021-11-15 13:40 UTC, majakurcius commented on docs/02-get-started/README.md
> +
```suggestion
```

I have doubts as to whether we should put this NOTE here. It's Get Started, it's supposed to be fairly concise and quick to do and it doesn't look great to require the user to do some switching before they even started installing Kyma. 
Maybe, for the sake of GSG, we can just use version 1.19 of Kubernetes here? The installation step links to the main Kyma installation doc anyway "for other ways to install Kyma", so the user will be able to see the CAUTION note there.

Optionally, we can link to that installation doc two lines below like this:
```
[k3d](https://k3d.io) (v4.0.0 or higher with [Kubernetes](https://kubernetes.io/docs/setup/) v1.19 - for higher versions, see [this tutorial](../../04-operation-guides/operations/02-install-kyma.md)
```

2021-11-15 15:04 UTC, veichtj approved these changes

2021-11-16 07:18 UTC, majakurcius approved these changes

2021-11-16 07:20 UTC, merged