Update serverless components
kyma-project/kyma pull request #12590
Opened 2021-11-10 13:23 UTC by pPrecel

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/12578
https://github.com/kyma-project/kyma/pull/12589

2021-11-10 14:09 UTC, dbadura requested changes
Please chery-pick changes to 1.24 branch and then bump it with output of `post-main-rel124` jobs

2021-11-10 19:53 UTC, dbadura commented
/test pre-rel124-kyma-gke-upgrade

2021-11-11 10:36 UTC, m00g3n approved these changes
LGTM

2021-11-12 07:54 UTC, dbadura approved these changes

2021-11-12 09:06 UTC, merged