WIP : Expose istio /healthz/ready endpoint to public
kyma-project/kyma pull request #12754
Opened 2021-12-01 02:53 UTC by life0215

**Description**

Changes proposed in this pull request:

- Expose istio /healthz/ready endpoint to public, so it's possible add external monitor for kyma runtime

**Related issue(s)**

2021-12-02 12:22 UTC, strekm requested changes
please move this vs to istio-configuration component

2021-12-09 12:10 UTC, cnvergence commented
This is a valid point, deploying VS before the gateway would require some time for the Istio to update its state.
If it is not acceptable, I'm okay with leaving this VS in the certificates.

2021-12-10 08:17 UTC, cnvergence approved these changes

2021-12-13 22:59 UTC, JackCheng01 commented
> Merging can be performed automatically once the requested changes are addressed.
Hi, @strekm  Can you help review again?

2021-12-15 07:53 UTC, strekm approved these changes

2021-12-15 08:29 UTC, merged