Replace individual code owners with teams
kyma-project/kyma pull request #12837
Opened 2021-12-10 11:24 UTC by pbochynski

**Description**

Changes proposed in this pull request:

- propose new CODEOWNERS file structure based on area teams

**Related issue(s)**
- https://github.com/kyma-project/community/issues/613

2022-01-27 09:17 UTC, mmitoraj requested changes

2022-01-27 09:17 UTC, mmitoraj commented on CODEOWNERS
> +*.md @kyma-project/documentation
The team's name is `technical-writers`
```suggestion
*.md @kyma-project/technical-writers
```

2022-01-27 09:17 UTC, mmitoraj commented on CODEOWNERS
> +/docs/ @kyma-project/documentation
The team's name is `technical-writers`
```suggestion
/docs/ @kyma-project/documentation
```

2022-01-27 09:17 UTC, mmitoraj commented on CODEOWNERS
> +milv.config.yaml @m00g3n @pPrecel @kyma-project/documentation
The team's name is `technical-writers`
```suggestion
milv.config.yaml @m00g3n @pPrecel @kyma-project/technical-writers
```

2022-03-14 13:13 UTC, pbochynski commented
We go with slightly different approach: https://github.com/kyma-project/kyma/pull/13543
This work won't be continued.

2022-03-14 13:13 UTC, closed without merging