update telemetry operator resource
kyma-project/kyma pull request #12931
Opened 2021-12-23 14:16 UTC by dennis-ge

**Description**

Changes proposed in this pull request:

- updates the telemetry resource to new LogPipeline CRD
- small updates in the fast integration `telemetry-test`
- needs to be merged after https://github.com/kyma-project/kyma/pull/12910

**Related issue(s)**

2022-01-10 11:08 UTC, dennis-ge commented
/test pre-main-kyma-integration-k3d-central-app-connectivity

2022-01-10 11:22 UTC, dennis-ge commented
/test pre-main-kyma-gardener-gcp-eventing

2022-01-11 08:52 UTC, dennis-ge commented
/test pre-main-kyma-integration-k3d-compass-dev
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2022-01-11 09:57 UTC, dennis-ge commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2022-01-11 10:09 UTC, dennis-ge commented
/test pre-main-kyma-integration-k3d-compass-dev

2022-01-11 10:18 UTC, chrkl requested changes

2022-01-11 10:18 UTC, chrkl commented on resources/telemetry/charts/operator/templates/deployment.yaml
> +            - --parser-cm-name={{ .Release.Name }}-{{ .Values.logProcessor }}-parsers
We should align the parsers volume mount in the fluent-bit chart values with this one. Also double-check the other ConfigMaps.

2022-01-12 11:11 UTC, dennis-ge commented
/test pre-main-kyma-gardener-azure-alpha-eval

2022-01-12 15:56 UTC, dennis-ge commented
/test pre-main-kyma-gardener-azure-alpha-eval

2022-01-12 16:58 UTC, chrkl approved these changes

2022-01-13 08:08 UTC, lindnerby approved these changes

2022-01-13 08:48 UTC, chrkl commented
/retest

2022-01-13 09:18 UTC, merged