Implement readiness probe for NATS publisher based on connection status of NATS server(s)
kyma-project/kyma pull request #13120
Opened 2022-01-19 16:09 UTC by marcobebway

**Description**

Implement readiness probe for the NATS publisher proxy based on the connection status of the NATS server(s).

**Related issue(s)**
- https://github.com/kyma-project/kyma/issues/13029

2022-01-20 21:45 UTC, marcobebway commented
/test pre-main-kyma-skr-eventing

2022-01-20 23:45 UTC, marcobebway commented
/retest

2022-01-21 07:10 UTC, marcobebway commented
/retest

2022-01-21 07:59 UTC, k15r commented on components/event-publisher-proxy/pkg/sender/nats.go
> +// NatsMessageSender is responsible for sending messages over HTTP.
😄

2022-01-21 08:31 UTC, k15r commented
the error message sent to the user in case the connection to nats is not working could be improved:
```
Kyma application API responded with status 500 { "status": 500, "message": "connection status not connected: RECONNECTING" }```

2022-01-25 08:43 UTC, nachtmaar commented
/test pre-main-kyma-skr-eventing

2022-02-24 19:50 UTC, marcobebway commented
/test pre-main-kyma-integration-k3d-telemetry

2022-02-24 19:51 UTC, marcobebway commented
/retest

2022-02-28 15:17 UTC, FriedrichWilken requested changes
there is an issue when port forwarding to epp, while having not nats backend up: when sending an event it gets a 2xx status, while it should be 4xx or 5xx.

2022-03-01 08:19 UTC, marcobebway commented
> there is an issue when port forwarding to epp, while having not nats backend up: when sending an event it gets a 2xx status, while it should be 4xx or 5xx.

Thanks for reporting this. I pushed a [commit](https://github.com/kyma-project/kyma/pull/13120/commits/1fc7ebeaaaa6b346bf172231bcb00691accbe436) for the fix.

2022-03-01 11:42 UTC, marcobebway commented
> there is an issue when port forwarding to epp, while having not nats backend up: when sending an event it gets a 2xx status, while it should be 4xx or 5xx.

Done.

2022-03-01 12:05 UTC, FriedrichWilken approved these changes

2022-03-01 12:22 UTC, merged