Move the `serverless-bench` folder
kyma-project/kyma pull request #13236
Opened 2022-02-01 13:44 UTC by pPrecel

**Description**

Changes proposed in this pull request:

- as in the title

**Related issue(s)**

- https://github.com/kyma-project/third-party-images/pull/176

2022-02-03 12:55 UTC, dbadura requested changes

2022-02-03 12:55 UTC, dbadura commented on tests/serverless-bench/run-benchmarks.sh
> +    -f /home/locust/locust.py --csv "${FUNCTION}" --logfile /dev/null
Can we use relative path?

2022-02-03 12:55 UTC, dbadura commented on tests/serverless-bench/locust.py
> +class Python38Test(HttpUser):
It can be named `StressTest`

2022-02-03 12:55 UTC, dbadura commented on CODEOWNERS
> +/tests/serverless-bench/ @m00g3n @pPrecel @dbadura @moelsayed
`cortney`?

2022-02-03 15:48 UTC, dbadura commented on tests/serverless-bench/Dockerfile
> +&& pip install . \
I will fix it in separate PR.

2022-02-03 15:48 UTC, dbadura approved these changes

2022-02-04 08:28 UTC, grego952 submitted a review, later dismissed

2022-02-04 13:40 UTC, dbadura approved these changes

2022-02-04 13:44 UTC, grego952 approved these changes

2022-02-04 16:10 UTC, merged