Add tracing sdk to function runtimes
kyma-project/kyma pull request #13348
Opened 2022-02-10 14:17 UTC by pPrecel

**Description**

Changes proposed in this pull request:

- Extend all function runtimes by adding the tracer object

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/11327

2022-02-15 13:29 UTC, pPrecel commented
/retest

2022-02-15 15:32 UTC, pPrecel commented
/test all

2022-02-15 21:40 UTC, pPrecel commented
/test all

2022-02-15 22:18 UTC, pPrecel commented
/test all

2022-02-15 22:31 UTC, pPrecel commented
/test all

2022-02-15 22:54 UTC, pPrecel commented
/test all

2022-02-16 07:51 UTC, pPrecel commented
/retest

2022-02-16 10:01 UTC, pPrecel commented
/test all

2022-02-16 15:57 UTC, pPrecel commented
/test all

2022-02-16 18:38 UTC, pPrecel commented
/test all

2022-02-16 21:13 UTC, pPrecel commented
/test all

2022-02-16 21:52 UTC, pPrecel commented
/test all

2022-02-18 12:10 UTC, pPrecel commented
/test all

2022-02-21 19:52 UTC, pPrecel commented
I've tested all functionality using the [http-https-echo](https://hub.docker.com/r/mendhak/http-https-echo) to receive and display information about requests outgoing from the serverless functions and the KymaCLI to easily deploy each runtime.

1. To configure `http-https-echo` service apply the following yaml:

echo.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-echo
  name: my-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-echo
    spec:
      containers:
      - image: mendhak/http-https-echo:23
        name: http-https-echo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-echo
  name: my-echo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-echo
  type: ClusterIP
status:
  loadBalancer: {}
```

2. For the nodejs12/14 runtimes:

config.yaml
```yaml
name: function-exciting-rafal8
namespace: default
runtime: nodejs14
source:
    sourceType: inline
apiRules:
    - rules:
        - methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - HEAD
```

handler.js
```javascript
const api = require('@opentelemetry/api');

module.exports = {
    main: function (event, context) {
        console.log('starting...');
        req = event.extensions.request;

        if (req.headers['x-b3-sampled'] == 0) {
            console.log("sampled value is equal 0... skipping :(")
            return
        }

        console.log("headers:", req.headers);
        
        span = event.tracer.startSpan('my-first-own-span', {});
        console.log("span:", span);
        span.addEvent('bar');

        for (let i = 0; i < 10000000; i++){};
        
        span2 = event.tracer.startSpan('my-sec-own-span', {});
        console.log("span2:", span2);

        for (let i = 0; i < 10000000; i++){};

        span2.addEvent('good job');

        api.context.with(api.setSpan(api.context.active(), span), () => {
            span3 = event.tracer.startSpan('my-sec-of-the-first-own-span', {
            });

            console.log("span3:", span2);

            var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
            const Http = new XMLHttpRequest();
            const url='http://my-echo.default.svc.cluster.local:8080';
            Http.open("GET", url);
            Http.send();
            Http.onreadystatechange = (e) => {
                console.log(Http.responseText)
            }

            for (let i = 0; i < 10000000; i++){}

            span3.addEvent('good job');
            span3.end();
        })

        for (let i = 0; i < 10000000; i++){};

        span2.end();
        
        span.addEvent('almost end');
        span.end();

        console.log("tracing initialized");
        
        return 'Hello Serverless'
    }
}
```

package.json
```json
{
  "name": "function-exciting-rafal8",
  "version": "0.0.1",
  "dependencies": {
    "@opentelemetry/api": "^0.18.0",
    "xmlhttprequest": "^1.8.0"
  }
}
```

3. Dor the python39 runtime:

config.yaml
```yaml
name: function-epic-maciej1
namespace: default
runtime: python39
source:
    sourceType: inline
apiRules:
    - rules:
        - methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - HEAD
```

handler.py
```python
import requests


def main(event, context):
    ce = event.ceHeaders["extensions"]
    
    if ce["request"].headers.get('X-B3-Sampled') == "0":
        print("sampled 0 :( skipping")
    else:
        with event.tracer.start_as_current_span("fir-span"):
            event.tracer.start_span("fir-of-fir-span")
            with event.tracer.start_as_current_span("sec-of-fir-span"):
                print("Hello OpenTelemetry with Zipkin from the sec-of-fir-span!")
                r = requests.get('http://my-echo.default.svc.cluster.local:8080')
                print(r.text)
        with event.tracer.start_as_current_span("sec_span"):
            print("hello from sec span")

    return "hello world" 
```

2022-02-21 20:25 UTC, pPrecel commented
/retest

2022-02-22 13:54 UTC, pPrecel commented
/retest

2022-02-22 14:09 UTC, pPrecel commented
/reteest

2022-02-22 14:09 UTC, pPrecel commented
/retest

2022-02-22 20:00 UTC, pPrecel commented
/retest

2022-02-23 12:38 UTC, pPrecel commented
/retest

2022-02-23 15:51 UTC, pPrecel commented
/retest

2022-02-23 16:14 UTC, pPrecel commented
/retest

2022-02-24 06:53 UTC, pPrecel commented
/retest

2022-02-24 07:53 UTC, pPrecel commented
/retest

2022-02-24 13:07 UTC, pPrecel commented
/retest

2022-02-24 20:35 UTC, Cortey approved these changes

2022-02-25 07:51 UTC, pPrecel commented
/retest

2022-03-01 13:59 UTC, dbadura requested changes
I revieweed the Python part

2022-03-02 07:09 UTC, pPrecel commented on components/function-runtimes/python39/kubeless/tracing.py
> +        res = requests.get(jaegerEndpoint)
good point

2022-03-02 07:49 UTC, pPrecel commented on components/function-runtimes/python39/kubeless/tracing.py
> +        # 405 is the right status code for the GET method if jaeger service exists
`405` status means that [Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405). There is no info in the documentation that this endpoint would return this status. But this results from the HTTP servers architecture. If the method would be not allowed, then the server will return the `405` status code. Here is info about the POST method which is the only allowed:
https://github.com/jaegertracing/jaeger/blob/7872d1b07439c3f2d316065b1fd53e885b26a66f/cmd/collector/app/handler/http_handler.go#L60

2022-03-02 08:50 UTC, dbadura commented on components/function-runtimes/python39/kubeless/tracing.py
> +        # 405 is the right status code for the GET method if jaeger service exists
I would add description of this to the code to minimize confusion

2022-03-02 09:05 UTC, dbadura commented on components/function-runtimes/python39/kubeless/tracing.py
> +        # 405 is the right status code for the GET method if jaeger service exists
I think we should we should use `health` endpoint: 
https://github.com/jaegertracing/jaeger/blob/7872d1b07439c3f2d316065b1fd53e885b26a66f/pkg/healthcheck/handler.go

2022-03-02 09:27 UTC, pPrecel commented
/test all

2022-03-02 09:47 UTC, pPrecel commented
/retest

2022-03-02 21:35 UTC, pPrecel commented
/retest

2022-03-03 13:43 UTC, dbadura submitted a review, later dismissed
I reviewed python part

2022-03-03 14:42 UTC, pPrecel commented
/retest

2022-03-04 08:01 UTC, pPrecel commented
/test license/cla

2022-03-04 08:28 UTC, dbadura approved these changes

2022-03-04 09:37 UTC, Cortey approved these changes

2022-03-04 12:18 UTC, pPrecel commented
/retest

2022-03-04 12:31 UTC, merged