Removal of the Application Registry, Connector Service and Connection Token Handler sources
kyma-project/kyma pull request #13891
Opened 2022-04-11 07:24 UTC by mvshao

**Description**
We are planning to remove the Application Registry, Connector Service and Connection Token Handler, so in this case, we won't need these components anymore. 

Changes proposed in this pull request:

- adjust the Connectivity Validator in non OS flow
- remove the Application Registry, Connector Service and Connection Token Handler sources

**Related issue(s)**
#13718

2022-04-15 07:46 UTC, Disper commented
/assign @Maladie

2022-04-15 10:17 UTC, mvshao commented
/assign @mvshao

2022-04-21 08:03 UTC, koala7659 commented
/cc @akgalwas

2022-04-22 13:18 UTC, akgalwas commented on components/application-connectivity-validator/cmd/applicationconnectivityvalidator/options.go
> +		"--appName=%s "+
Be aware that removing this from the application's code is not enough. It should be removed from deployment.

2022-04-22 14:02 UTC, akgalwas commented on components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
> -		options.appRegistryPathPrefix,
Be aware that removing this from the application's code is not enough. It should be removed from deployment.

2022-04-26 07:24 UTC, akgalwas submitted a review, later dismissed

2022-04-26 08:19 UTC, majakurcius commented on components/central-application-connectivity-validator/README.md
>  The Central Application Connectivity Validator validates client certificate subjects.
```suggestion
The Central Application Connectivity Validator validates client certificate subjects in the Compass mode of Kyma.
```

2022-04-26 09:04 UTC, majakurcius submitted a review, later dismissed

2022-04-27 06:50 UTC, majakurcius submitted a review, later dismissed

2022-05-04 13:33 UTC, koala7659 requested changes
Please remove also sources for component `application-connectivity-certs-setup-job `

2022-05-04 13:52 UTC, koala7659 submitted a review, later dismissed
LGTM

2022-05-21 08:52 UTC, koala7659 commented
/retest

2022-05-23 06:46 UTC, franpog859 commented
/retest

2022-05-23 07:34 UTC, koala7659 commented
/test all

2022-05-23 12:49 UTC, koala7659 commented
/test all

2022-05-23 13:13 UTC, koala7659 approved these changes
LGTM

2022-05-23 13:15 UTC, franpog859 approved these changes

2022-05-24 06:07 UTC, franpog859 commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass
/test pre-main-kyma-integration-k3d-compass-dev

2022-05-24 06:29 UTC, grego952 approved these changes

2022-05-24 06:30 UTC, klaudiagrz approved these changes

2022-05-24 06:46 UTC, merged