Prepare for Github workflow
kyma-project/kyma pull request #14075
Opened 2022-04-25 07:19 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- add CODEOWNERS file, updated with the current data
- ...

**Related issue(s)**

/assign
/retest

2022-04-25 08:00 UTC, Halamix2 commented
/retest

2022-04-25 14:38 UTC, dekiel requested changes

2022-04-25 14:38 UTC, dekiel commented on CODEOWNERS
> +*.md @klaudiagrz @mmitoraj @majakurcius @alexandra-simeonova @NHingerl @grego952
This line should be at the end to take precedence over all other matches.

2022-04-25 14:49 UTC, dekiel commented
/lgtm
/approve

2022-04-26 06:35 UTC, majakurcius commented on CODEOWNERS
> +milv.config.yaml @m00g3n @pPrecel @kwiatekus @moelsayed @cortey @klaudiagrz @mmitoraj @majakurcius @alexandra-simeonova @NHingerl @grego952
```suggestion
milv.config.yaml @m00g3n @pPrecel @kwiatekus @moelsayed @cortey @klaudiagrz @mmitoraj @majakurcius @NHingerl @grego952
```

2022-04-26 06:41 UTC, Halamix2 commented on CODEOWNERS
> +milv.config.yaml @m00g3n @pPrecel @kwiatekus @moelsayed @cortey @klaudiagrz @mmitoraj @majakurcius @alexandra-simeonova @NHingerl @grego952
Done

2022-04-26 06:50 UTC, majakurcius approved these changes

2022-04-26 07:02 UTC, FriedrichWilken reviewed
Here are some proposed changes. There was a missing "@" and we need to remove @radufa from the code owner.

2022-04-26 07:02 UTC, FriedrichWilken commented on CODEOWNERS
> +/components/eventing-controller @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @radufa @lilitgh
```suggestion
/components/eventing-controller @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```

2022-04-26 07:02 UTC, FriedrichWilken commented on CODEOWNERS
> +/installation/resources/crds/eventing @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @radufa @lilitgh
```suggestion
/installation/resources/crds/eventing @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```

2022-04-26 07:02 UTC, FriedrichWilken commented on CODEOWNERS
> +/resources/eventing @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @radufa @lilitgh
```suggestion
/resources/eventing @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```

2022-04-26 08:21 UTC, koala7659 commented
Two comments:

1. I believe `framefrog` team should be mentioned as owners of fast integration tests directory. At least in the case of `/tests/fast-integration/skr-test` of the best full directory `/tests/fast-integration`.  As a team responsible for application connectivity we maintain and fix them regularly.
2.  There is no directory `/tests/fast-integration/skr-test-without-sc` on the main branch. Can you check if this entry is valid?

2022-04-26 08:28 UTC, FriedrichWilken commented on CODEOWNERS
> +/tests/fast-integration/eventing-test @yma-project/eventing
```suggestion
/tests/fast-integration/eventing-test @kyma-project/eventing
```

2022-04-26 09:09 UTC, FriedrichWilken commented on CODEOWNERS
> +/tests/fast-integration/eventing-test @kyma-project/eventing
```suggestion
@k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```

2022-04-26 09:16 UTC, FriedrichWilken commented on CODEOWNERS
> +@k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```suggestion

/tests/fast-integration/eventing-test @k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
```

2022-04-26 09:16 UTC, FriedrichWilken commented on CODEOWNERS
> +@k15r @nachtmaar @marcobebway @pxsalehi @mfaizanse @friedrichwilken @vladislavpaskar @raypinto @lilitgh
sorry, my bad

2022-04-26 09:33 UTC, lilitgh commented on CODEOWNERS
> +/resources/monitoring @a-thaler @clebs @rakesh-garimella @skhalash @jeremyharisch @chrkl @lindnerby @dennis-ge @lilitgh
```suggestion
/resources/monitoring @a-thaler @rakesh-garimella @skhalash @chrkl @lindnerby @dennis-ge @lilitgh
```

2022-04-26 09:33 UTC, lilitgh commented on CODEOWNERS
> +/resources/telemetry @a-thaler @clebs @rakesh-garimella @skhalash @jeremyharisch @chrkl @lindnerby @dennis-ge @lilitgh
```suggestion
/resources/telemetry @a-thaler @rakesh-garimella @skhalash @chrkl @lindnerby @dennis-ge @lilitgh
```

2022-04-26 09:33 UTC, lilitgh commented on CODEOWNERS
> +/resources/tracing @a-thaler @clebs @rakesh-garimella @skhalash @jeremyharisch @chrkl @lindnerby @dennis-ge @lilitgh
```suggestion
/resources/tracing @a-thaler @rakesh-garimella @skhalash @chrkl @lindnerby @dennis-ge @lilitgh
```

2022-04-26 12:47 UTC, merged