Prohibited matches in filters and outputs in telemetry-operator
kyma-project/kyma pull request #14767
Opened 2022-07-06 14:16 UTC by Teneroy

**Description**

Changes proposed in this pull request:

- Prohibited "Match" in filters and outputs
- Fixed validator tests
- Refactored tests to adapt to the new logic
- Changed examples

**Related issue(s)**
#14562

2022-07-06 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=14767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=14767) before we can accept your contribution.<br/><hr/>**Aleksei Chernyshov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=14767) it.</sub>

2022-07-06 17:30 UTC, Teneroy commented
/retest

2022-07-06 17:37 UTC, Teneroy commented
/test pre-main-kyma-skr-eventing

2022-07-06 18:07 UTC, Teneroy commented
/test pre-main-kyma-gardener-azure-alpha-eval

2022-07-06 18:27 UTC, Teneroy commented
/test pre-main-kyma-gardener-azure-alpha-prod

2022-07-07 07:28 UTC, Teneroy commented
/test pre-main-kyma-gardener-azure-alpha-prod

2022-07-07 08:46 UTC, Teneroy commented
/test pre-main-kyma-skr-eventing

2022-07-07 09:55 UTC, NHingerl submitted a review, later dismissed

2022-07-07 11:57 UTC, Teneroy commented
/retest

2022-07-07 12:49 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2022-07-07 14:27 UTC, chrkl requested changes

2022-07-07 14:27 UTC, chrkl commented on components/telemetry-operator/internal/validation/plugin_validator_test.go
> +	assert.Contains(t, err.Error(), "plugin 'grep' contains match condition. Match conditions are forbidden")
Looks like the test before did not what the name suggests. Let's split it to two tests. One to validate that a LogPipeline that has a `match` expression is rejected and one that tests for the forbidden `lua` filter.

2022-07-07 14:27 UTC, chrkl commented on components/telemetry-operator/internal/validation/plugin_validator_test.go
> +	assert.Contains(t, err.Error(), "plugin 'es' contains match condition. Match conditions are forbidden")
Same here, let's also test that the `es` output is forbidden.

2022-07-08 07:28 UTC, chrkl approved these changes

2022-07-08 07:31 UTC, merged