Remove the omitempty from SubscriptionStatus CleanEventTypes
kyma-project/kyma pull request #14881
Opened 2022-07-21 14:41 UTC by marcobebway

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/14293.

2022-07-21 15:10 UTC, marcobebway commented
/test pre-main-kyma-validate-image-existence

2022-07-21 15:25 UTC, marcobebway commented
/retest-required

2022-07-21 19:33 UTC, marcobebway commented
/retest-required

2022-07-21 20:36 UTC, marcobebway commented
/retest

2022-07-21 21:09 UTC, marcobebway commented
/retest

2022-07-21 21:44 UTC, marcobebway commented
/retest

2022-07-25 12:19 UTC, friedrichwilken requested changes

2022-07-25 13:26 UTC, marcobebway commented on components/eventing-controller/api/v1alpha1/subscription_types.go
> +	a := (Alias)(s)
Done

2022-07-25 13:26 UTC, marcobebway commented on components/eventing-controller/api/v1alpha1/subscription_types.go
> +	type Alias Subscription
Done

2022-07-25 13:28 UTC, marcobebway commented
/hold

2022-07-25 13:40 UTC, friedrichwilken approved these changes

2022-07-25 13:40 UTC, friedrichwilken commented
/lgtm

2022-07-25 13:41 UTC, marcobebway commented
/retest-required

2022-07-25 13:42 UTC, marcobebway commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2022-07-26 09:48 UTC, marcobebway commented
/hold cancel

2022-07-26 14:33 UTC, marcobebway commented
/test pre-main-kyma-integration-k3d-central-app-connectivity-compass

2022-07-26 14:54 UTC, merged