Lua de-dotting filter
kyma-project/kyma pull request #14927
Opened 2022-07-26 18:38 UTC by Teneroy

**Description**

Changes proposed in this pull request:

- Moved lua script to separate file 
- Added filter  
- Added tests

**Related issue(s)**

2022-07-28 15:53 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d

2022-07-28 15:54 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-07-29 09:41 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d

2022-07-29 09:53 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-07-29 12:02 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-08-01 11:02 UTC, dennis-ge commented
/retest

2022-08-01 15:01 UTC, chrkl requested changes

2022-08-02 06:57 UTC, dennis-ge commented on components/telemetry-operator/internal/fluentbit/config_builder.go
> +script 				  /fluent-bit/scripts/filter-script.lua
@chrkl I replaced the tabs with spaces. The intendation is on the same level as the `PermanentFilterTemplate` and `EmitterTemplate`, should we reduce it to 1 space?

2022-08-02 07:55 UTC, chrkl approved these changes

2022-08-02 09:05 UTC, dennis-ge commented
/retest

2022-08-02 09:16 UTC, merged