Disabling istio sidecars injection
kyma-project/kyma pull request #14995
Opened 2022-08-03 09:25 UTC by dariusztutaj

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
#1126

2022-08-04 10:41 UTC, dariusztutaj commented
/retest

2022-08-17 08:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=14995) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=14995) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dariusztutaj<br/>:x: SamehMKhattab<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=14995) it.</sub>

2022-08-17 09:28 UTC, barchw requested changes

2022-08-17 09:28 UTC, barchw commented on docs/01-overview/main-areas/service-mesh/smsh-99-useful-links.md
> +  - [Disable Istio Sidecar Proxy Injection](../../../04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md)
```suggestion
  - [Enable Istio Sidecar Proxy Injection](../../../04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md)
```

2022-08-17 09:58 UTC, SamehMKhattab commented on docs/04-operation-guides/troubleshooting/service-mesh/smsh-03-istio-no-sidecar.md
> +By default, Kyma has sidecar injection disabled - a sidecar is not injected to any Pod in a cluster. For more information, read the document about [enabling Istio sidecar proxy injection](../../opera
```suggestion
By default, Kyma has sidecar injection disabled - there is no automatic sidecar injection into any Pod in a cluster. For more information, read the document about [enabling Istio sidecar proxy injection](../../operations/smsh-01-istio-enable-sidecar-injection.md).
```

2022-08-17 09:58 UTC, SamehMKhattab commented on docs/04-operation-guides/troubleshooting/service-mesh/smsh-04-istio-sidecar-version.md
> +By default, Kyma has sidecar injection disabled - a sidecar is not injected to any Pod in a cluster. For more information, read the document about [disabling Istio sidecar proxy injection](../../oper
```suggestion
By default, Kyma has sidecar injection disabled - there is no automatic sidecar injection into any Pod in a cluster. For more information, read the document about [enabling Istio sidecar proxy injection](../../operations/smsh-01-istio-enable-sidecar-injection.md).
```

2022-08-17 09:58 UTC, SamehMKhattab commented on docs/05-technical-reference/00-architecture/svls-01-architecture.md
> +**CAUTION:** Serverless imposes some requirements on the setup of Namespaces. For example, if you create a new Namespace you have to enable sidecar injection in it, as Serverless requires Istio for o
```suggestion
**CAUTION:** Serverless imposes some requirements on the setup of Namespaces. For example, if you create a new Namespace you have to enable sidecar injection in it, as Serverless needs Istio for other resources to communicate with Functions correctly. Also, if you apply custom [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/) for a new Namespace, they must be higher than or equal to the [limits for building Jobs' resources](../05-configuration-parameters/svls-01-serverless-chart.md).
```

2022-08-17 09:58 UTC, SamehMKhattab commented on docs/05-technical-reference/00-architecture/svls-01-architecture.md
> +**NOTE:** To enable Istio sidecar proxy injection which is disabled on the Kyma clusters by default, set the `istio-injection=enabled` flag at the Namespace level.
```suggestion
**NOTE:** To enable Istio sidecar proxy injection, which is disabled on the Kyma clusters by default, set the `istio-injection=enabled` flag at the Namespace level.
```

2022-08-17 10:28 UTC, dariusztutaj commented
/test pre-main-kyma-integration-k3d

2022-08-17 11:28 UTC, barchw approved these changes

2022-08-18 07:20 UTC, dariusztutaj commented
Too many issues with raising. PR will be replaced with new one.

2022-08-18 07:20 UTC, closed without merging