delete minor unreachable code caused by log.Fatal
kyma-project/kyma pull request #15061
Opened 2022-08-09 14:23 UTC by Abirdcfly

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-08-09 14:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/kyma?pullRequest=15061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/kyma?pullRequest=15061) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/kyma?pullRequest=15061) it.</sub>

2022-10-04 08:24 UTC, mvshao requested changes
Changes in code look good to me! But you need to update the mock-app image version in `tests/components/application-connector/resources/charts/gateway-test/values.yaml` file.

2022-10-04 08:27 UTC, mvshao commented
/test all

2022-10-05 04:12 UTC, Abirdcfly commented
It looks like my error rebase brought in a large number of reviewers, and although it seems I corrected the error, those review requests were not cancelled. (bot bug?) 

I should close this pr and re-open another one. 

Sorry to bother everyone.

2022-10-05 04:12 UTC, closed without merging