Otters security fixes 2.6
kyma-project/kyma pull request #15178
Opened 2022-08-19 13:16 UTC by m00g3n

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-08-19 16:18 UTC, pPrecel commented on components/function-runtimes/python39/Dockerfile
> +	&& apk add --no-chacje --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main \
```suggestion
	&& apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main \
```

2022-08-22 10:49 UTC, m00g3n commented
/test all

2022-08-22 11:36 UTC, m00g3n commented
/test all

2022-08-22 12:42 UTC, dbadura requested changes
Bump images

2022-08-22 12:42 UTC, dbadura commented on components/function-runtimes/python39/Dockerfile
> +FROM alpine:3.16.2
We can use sha image:
```
# image base on alpine:3.16.2
FROM alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
```

2022-08-22 12:45 UTC, pPrecel submitted a review, later dismissed

2022-08-22 13:17 UTC, m00g3n commented on components/function-runtimes/python39/Dockerfile
> +FROM alpine:3.16.2
lets change this, thx

2022-08-22 22:15 UTC, pPrecel submitted a review, later dismissed

2022-08-23 07:10 UTC, pPrecel submitted a review, later dismissed

2022-08-23 08:18 UTC, dbadura approved these changes

2022-08-23 08:29 UTC, m00g3n commented
/test all

2022-08-23 08:50 UTC, dbadura commented
/test pre-main-serverless-integration-k3s

2022-08-23 09:13 UTC, pPrecel approved these changes

2022-08-23 09:38 UTC, dbadura commented
/test pre-main-kyma-integration-k3d

2022-08-23 10:08 UTC, merged