Adding pipeline to the emitter name to the graphana chart
kyma-project/kyma pull request #15374
Opened 2022-09-05 22:35 UTC by Teneroy

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-09-08 13:37 UTC, Teneroy commented
/retest

2022-09-09 10:18 UTC, Teneroy commented
/retest

2022-09-09 11:49 UTC, Teneroy commented
/retest

2022-09-09 12:18 UTC, Teneroy commented
/retest

2022-09-09 12:27 UTC, Teneroy commented
/retest

2022-09-12 10:06 UTC, Teneroy commented
/retest

2022-09-12 10:20 UTC, Teneroy commented
/retest

2022-09-12 10:45 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d

2022-09-15 12:42 UTC, Teneroy commented
/retest

2022-09-15 14:14 UTC, Teneroy commented
/retest

2022-09-15 14:33 UTC, Teneroy commented
/retest

2022-09-15 15:39 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d

2022-09-16 07:23 UTC, chrkl commented on resources/telemetry/charts/fluent-bit/values.yaml
> +        Alias tail-tele
Make "tail" a suffix to have it consistent.

2022-09-16 07:28 UTC, a-thaler commented on resources/telemetry/charts/fluent-bit/values.yaml
> +        Alias tail-dummy
Shouldn't it be called "null-dummy" as well as it is part of the "null" pipeline somehow

2022-09-16 07:29 UTC, chrkl commented on components/telemetry-operator/internal/fluentbit/config/builder/output.go
> +	pipelineName := ""
Use `var pipelineName string` (same below)

2022-09-16 16:02 UTC, skhalash requested changes

2022-09-20 11:27 UTC, Teneroy commented
/retest

2022-09-20 23:21 UTC, Teneroy commented
/retest

2022-09-20 23:24 UTC, Teneroy commented
/retest

2022-09-20 23:36 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d

2022-09-21 00:19 UTC, Teneroy commented
/retest

2022-09-21 00:57 UTC, Teneroy commented
/retest

2022-09-21 01:10 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-09-23 07:38 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-09-23 08:12 UTC, merged