Adding test for secret references
kyma-project/kyma pull request #15607
Opened 2022-09-22 17:04 UTC by Teneroy

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-09-22 17:11 UTC, Teneroy commented
/retest

2022-09-26 13:47 UTC, Teneroy commented
/test pre-kyma-components-telemetry-operator

2022-09-26 13:55 UTC, Teneroy commented
/retest

2022-09-26 16:16 UTC, lindnerby requested changes

2022-09-26 16:16 UTC, lindnerby commented on tests/fast-integration/telemetry-test/suite.js
> +      context('Custom HTTP Output', function() {
```suggestion
      context('Custom Output', function() {
```

2022-09-26 16:16 UTC, lindnerby commented on tests/fast-integration/telemetry-test/suite.js
> +        it('Should push logs to the HTTP mockserver', async function() {
```suggestion
        it('Should push logs to the custom HTTP mockserver', async function() {
```

2022-09-26 16:16 UTC, lindnerby commented on tests/fast-integration/telemetry-test/testdata/logpipeline-output-custom.yaml
> +  name: http-backend
```suggestion
  name: custom-output
```

2022-09-28 07:30 UTC, skhalash requested changes
Could you please add a secret rotation to your new test similar to https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/telemetry-test/suite.js#L145

2022-09-28 23:21 UTC, Teneroy commented
/retest

2022-09-29 00:04 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-09-29 12:08 UTC, Teneroy commented
/test pre-main-kyma-integration-k3d-telemetry

2022-09-29 14:27 UTC, lindnerby approved these changes

2022-10-04 08:48 UTC, skhalash approved these changes

2022-10-05 07:39 UTC, lindnerby commented
/test pre-main-kyma-integration-k3d

2022-10-05 08:15 UTC, merged