Ensure single trace pipeline
kyma-project/kyma pull request #16413
Opened 2022-12-21 12:01 UTC by skhalash

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-12-21 12:13 UTC, skhalash commented
/test all

2022-12-21 16:28 UTC, skhalash commented
/test all

2022-12-22 17:22 UTC, skhalash commented
/build all

2022-12-22 17:24 UTC, skhalash commented
/build all

2022-12-22 17:24 UTC, skhalash commented
/test all

2022-12-23 13:33 UTC, skhalash commented
/retest pre-main-kyma-integration-k3d-telemetry-alpha

2022-12-23 13:37 UTC, skhalash commented
/test pre-main-kyma-integration-k3d-telemetry-alpha

2022-12-23 14:18 UTC, skhalash commented
/test pre-main-kyma-integration-k3d-telemetry-alpha

2022-12-23 14:34 UTC, lindnerby requested changes

2022-12-23 14:34 UTC, lindnerby commented on components/telemetry-operator/controller/tracepipeline/controller.go
> +			// I am the owner
Can be removed

2022-12-23 14:55 UTC, skhalash commented on components/telemetry-operator/controller/tracepipeline/controller.go
> +			// I am the owner
True

2022-12-23 14:58 UTC, lindnerby approved these changes

2022-12-23 15:26 UTC, skhalash commented
/retest-required

2022-12-28 08:11 UTC, lindnerby commented
/retest-required

2022-12-28 12:57 UTC, lindnerby commented
/test pre-main-kyma-integration-k3d-telemetry-alpha

2022-12-28 13:15 UTC, lindnerby approved these changes

2022-12-28 13:17 UTC, merged