Auto-generate APIRule and Istio CRD docs
kyma-project/kyma pull request #17483
Opened 2023-05-12 12:13 UTC by nataliasitko

**Description**

Changes proposed in this pull request:

- update descriptions in APIRule and Istio CRDs
- generate tables from CRDs in Istio and APIRule technical reference docs
- update the table generation Makefile

**Related issue(s)**
- https://github.com/kyma-project/kyma/issues/17480

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                      description: Specifies the list of access strategies.
can we have here link to oathkeeper docu?

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                description: 	Specifies the Istio Gateway to be used.
formatting error?

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                      description: 	Specifies the path of the exposed service.
formatting error?

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                description: APIRuleResourceStatus .
Describes status of ORY Oathkeeper Rule

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                description: APIRuleResourceStatus .
Describes status of Istio VirtualService

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                    description: StatusCode .
Status code describing the ORY Oathkeeper Rule.

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                    description: StatusCode .
Status code describing the Istio VirtualService.

2023-05-12 12:42 UTC, strekm commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                    description: StatusCode .
Status code describing the APIRule.

2023-05-12 12:46 UTC, barchw requested changes

2023-05-12 13:09 UTC, nataliasitko commented on installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
> +                description: 	Specifies the Istio Gateway to be used.
fixed

2023-05-18 09:19 UTC, barchw requested changes

2023-05-18 09:19 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **rules.&#x200b;accessStrategies** (required) | \[\]object | Specifies the list of access strategies. The supported access strategies are [Oathkeeper](https://www.ory.sh/docs/oathkeeper/pipeline/au
The supported ones are all of those listed in https://www.ory.sh/docs/oathkeeper/pipeline/authn

2023-05-18 09:36 UTC, barchw requested changes

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;jwks_urls**  | \[\]string | . |
```suggestion
| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;jwks_urls**  | \[\]string | Array of URLs from which Ory Oathkeeper can retrieve JSON Web Keys for validating JSON Web Token. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;trusted_issuers**  | \[\]string | . |
```suggestion
| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;trusted_issuers**  | \[\]string | If `trusted_issuers` is set, the JWT must contain a value for claim `iss` that matches exactly (case-sensitive) one of the values of `trusted_issuers` |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **authorizationPolicyStatus.&#x200b;code**  | string | StatusCode . |
```suggestion
| **authorizationPolicyStatus.&#x200b;code**  | string | Status code describing Istio Authorization Policy sub resource. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **authorizationPolicyStatus**  | object | APIRuleResourceStatus . |
```suggestion
| **authorizationPolicyStatus**  | object | Describes the status of Istio Authorization Policy sub resource. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **authorizationPolicyStatus.&#x200b;desc**  | string | . |
```suggestion
| **authorizationPolicyStatus.&#x200b;desc**  | string | Explains the status of Istio Authorization Policy sub resource. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **lastProcessedTime**  | string | . |
```suggestion
| **lastProcessedTime**  | string | Timestamp for when the APIRule was last processed by API Gateway controller. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **observedGeneration**  | integer | . |
```suggestion
| **observedGeneration**  | integer | The generation of the resource that was observed by API Gateway controller. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **requestAuthenticationStatus**  | object | APIRuleResourceStatus . |
```suggestion
| **requestAuthenticationStatus**  | object | Describes the status of Istio Request Authentication sub resource. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **requestAuthenticationStatus.&#x200b;code**  | string | StatusCode . |
```suggestion
| **requestAuthenticationStatus.&#x200b;code**  | string | Status code describing the state of Istio Authorization Policy sub resource . |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **requestAuthenticationStatus.&#x200b;desc**  | string | . |
```suggestion
| **requestAuthenticationStatus.&#x200b;desc**  | string | Explains the status of Istio Request Authentication sub resource. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;jwks_urls**  | \[\]string | . |
```suggestion
| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;jwks_urls**  | \[\]string | Array of URLs from which Ory Oathkeeper can retrieve JSON Web Keys for validating JSON Web Token. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;trusted_issuers**  | \[\]string | . |
```suggestion
| **rules.&#x200b;accessStrategies.&#x200b;config.&#x200b;trusted_issuers**  | \[\]string | If `trusted_issuers` is set, the JWT must contain a value for claim `iss` that matches exactly (case-sensitive) one of the values of `trusted_issuers`. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **observedGeneration**  | integer | . |
```suggestion
| **observedGeneration**  | integer | The generation of the resource that was observed by API Gateway controller. |
```

2023-05-18 09:36 UTC, barchw commented on docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
> +| **lastProcessedTime**  | string | . |
```suggestion
| **lastProcessedTime**  | string | Timestamp for when the APIRule was last processed by API Gateway controller. |
```

2023-05-18 13:56 UTC, barchw submitted a review, later dismissed

2023-05-19 08:55 UTC, barchw approved these changes
/woof

2023-05-19 09:10 UTC, pbochynski approved these changes

2023-05-19 10:07 UTC, IwonaLanger approved these changes

2023-05-19 10:21 UTC, merged