fix application-connector-validator caching
kyma-project/kyma pull request #17957
Opened 2023-08-09 14:39 UTC by m00g3n

**Description**

Changes proposed in this pull request:

- fix cache miss issue

**Related issue(s)**

see also: https://github.com/kyma-project/test-infra/pull/8606

2023-08-10 17:54 UTC, m00g3n commented
/test all

2023-08-10 17:55 UTC, m00g3n commented
-

2023-08-11 08:18 UTC, Disper commented
Related PR job https://github.com/kyma-project/test-infra/pull/8606

2023-08-16 10:18 UTC, koala7659 requested changes
Please check my comment

2023-08-16 10:18 UTC, koala7659 commented on resources/application-connector/charts/central-application-connectivity-validator/values.yaml
> -    namespace: kyma-system
Please remove also `cacheExpirationSeconds` and `cacheCleanupIntervalSeconds`

2023-08-18 10:51 UTC, akgalwas approved these changes

2023-08-18 10:52 UTC, akgalwas commented
/retest

2023-08-18 10:52 UTC, koala7659 approved these changes

2023-08-18 11:08 UTC, merged