Rremove all application connector helm charts as they are managed now in the Application Connector module
kyma-project/kyma pull request #18367
Opened 2023-10-27 10:23 UTC by koala7659

2023-10-27 10:55 UTC, grego952 approved these changes

2023-11-02 11:04 UTC, m00g3n approved these changes
LGTM

2023-11-03 08:29 UTC, grego952 approved these changes

2023-11-06 08:29 UTC, ruanxin approved these changes

2023-11-06 09:38 UTC, a-thaler requested changes
The PR has no description at all, hard to review without proper context.

There is a CRD applications.applicationconnector.crd in the compass-agent folder, is that related and could be removed?

What is with dopcumentation, the docs folder contains a section about application connectivity

2023-11-07 08:13 UTC, a-thaler approved these changes

2023-11-07 08:27 UTC, merged