Add queries and mutation for GitRepository CRD in CBS
kyma-project/kyma pull request #9301
Opened 2020-08-25 11:28 UTC by magicmatatjahu

**Description**

Changes proposed in this pull request:

- Add queries and mutation for GitRepository CRD in CBS
- Add `newServerless` domain with generic Service etc -> old implementation will be rewrite in followup 

**Related issue(s)**
https://github.com/kyma-project/console/issues/1932

2020-09-04 09:01 UTC, aerfio requested changes
LGTM, just a small nitpick from my side here, overall good job

2020-09-04 10:24 UTC, magicmatatjahu commented on components/console-backend-service/internal/domain/serverless/function_converter.go
> +	if baseDir != "" || reference != "" {
Repository struct is optional in CRD (type of course) and baseDir and reference is also optional :)

2020-09-04 10:29 UTC, magicmatatjahu commented on components/console-backend-service/internal/domain/serverless/newserverless.go
> +func NewR(factory *resource.GenericServiceFactory) *NewResolver {
Yes, it's tricky, I know that, but in `New` function we resolve old Resolver :D I will think about usefull name.

2020-09-09 09:29 UTC, aerfio approved these changes

2020-09-11 11:04 UTC, merged