Add git function tutorial
kyma-project/kyma pull request #9379
Opened 2020-09-07 10:29 UTC by kfurgol

**Description**

Changes proposed in this pull request:

- Added tutorial on how to create a function using Git repository

**Related issue(s)**

2020-09-07 10:46 UTC, magicmatatjahu requested changes
Very good! :) I prefer use the function from organisation repo, not from account one of our contributors :)

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +      url: "https://github.com/pPrecel/public-gitops"
Please use the https://github.com/kyma-project/examples.git repository. It's better to ref to repo in organisation, not to repo in account one of our contributors.

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +      name: $NAME
Add also namespace `namespace: $NAMESPACE`

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +      name: $NAME
Add also namespace `namespace: $NAMESPACE`

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +>**NOTE** Auth possibility TODO
Please add correct indents (3 or 4 spaces)

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +      baseDir: js-handler
Change to `orders-service/function`

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +    >**NOTE** To see full spec, go to the xxx page
Go to https://github.com/kyma-project/examples/tree/master/orders-service/function

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +This tutorial shows how you can create a simple "Hello World!" Function from Git repository.
`This tutorial shows how you can create a Function from Git repository.` The function from `examples` repo is a more complex than `Hello World!` :)

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +3. Click **Connect Repository**,  fill in required fields and click **Connect**.
Click **Connect Repository**, fill the `Url` field with `https://github.com/kyma-project/examples.git` value and click **Connect**.

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +    >**NOTE** Auth possibility TODO
> **NOTE** If you want connect the private repository, change the `Authorization` field from `Public` to `Key` or `Basic` and fill the required fields -> Auth possibility link TODO

2020-09-07 10:46 UTC, magicmatatjahu commented on docs/serverless/08-02-create-git-function.md
> +3. In the pop-up box, change `Source type` to `From Repository`, fill in required fields and select **Create** to confirm changes.
5. In the pop-up box, change `Source type` to `From Repository`, select created Repository's name, fill the `Reference` field with `master` and `Base directory` field with `orders-service/function` values and select **Create** to confirm changes.

2020-09-10 06:00 UTC, kazydek reviewed
Added some comments & suggestions.

2020-09-10 06:00 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +    The new Function should have the `RUNNING` status in the list of all Functions under the **Functions** view.
```suggestion
    Make sure that new Function has the `RUNNING` status in the list of all Functions under the **Functions** view.
```

2020-09-10 06:40 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +title: Create a Function from Git Repository
```suggestion
title: Create a Function from Git repository sources
```

2020-09-10 10:28 UTC, kfurgol commented on docs/serverless/08-02-create-git-function.md
> +title: Create a Function from Git Repository
what about:
```suggestion
title: Create a Function from remote Git repository
```?

2020-09-10 10:32 UTC, kfurgol commented on docs/serverless/08-02-create-git-function.md
> +    >**NOTE** To see other authorization methods, go to the [documentation]().
Ok, but still I would like to mention right below that example there are other authentication methods that we support. Maybe something like 
```suggestion
    >**NOTE** Check the documentation to see other supported authentication methods.
```

?

2020-09-10 10:35 UTC, kfurgol commented on docs/serverless/08-02-create-git-function.md
> +3. Create a Function CR that specifies the Function's logic:
what about:
```suggestion
3. Create a Function CR that specifies the Function's logic and points to the directory with code and dependencies inside the given repository
```

?

2020-09-10 10:39 UTC, kfurgol commented on docs/serverless/08-02-create-git-function.md
> +   >**NOTE** To see other possible authorization methods, go to the [documentation]().
Again, as with the CLI example, I'd like to mention that we support more than one (basic in that specific case) authorization method

2020-09-10 11:42 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +1. Export these variables:
Sth is wrong with formatting: 
![image](https://user-images.githubusercontent.com/40655785/92724631-41403a80-f36b-11ea-878e-91bdef67fe2e.png)

2020-09-10 11:42 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +1. Create a Namespace or select one from the drop-down list in the top navigation panel.
A bit better, but it still needs updating:
![image](https://user-images.githubusercontent.com/40655785/92724755-69c83480-f36b-11ea-93c4-c86d827394c2.png)

2020-09-10 12:06 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +5. In the pop-up box, change `Source type` to `From Repository`, select created Repository's name, fill the `Reference` field with `master` and `Base directory` field with `orders-service/function` v
(I asked Maciek and it will be capitalized - as in other views)

2020-09-11 08:29 UTC, kazydek commented on docs/serverless/08-02-create-git-function.md
> +5. In the pop-up box, change `Source Type` to `From Repository`, select created Repository's name, fill the `Reference` field with `master` and `Base Directory` field with `orders-service/function` v
```suggestion
5. In the pop-up box, change `Source Type` to `From Repository`, select created Repository's name, fill in the `Reference` field with `master` and `Base Directory` field with `orders-service/function` values, and select **Create** to confirm changes.
```

2020-09-11 09:18 UTC, kazydek submitted a review, later dismissed

2020-09-11 09:43 UTC, magicmatatjahu approved these changes

2020-09-11 09:54 UTC, kazydek approved these changes

2020-09-11 12:50 UTC, merged