Disable smoke tests on minikube
kyma-project/kyma pull request #9382
Opened 2020-09-07 12:38 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- Disable Console smoke tests on minikube.

**Related issue(s)**

2020-09-07 13:23 UTC, dariadomagala requested changes

2020-09-07 13:23 UTC, dariadomagala commented on installation/resources/installer-config-local.yaml.tpl
> +apiVersion: v1
this line is not needed

2020-09-07 13:23 UTC, dariadomagala commented on installation/resources/installer-config-local.yaml.tpl
> +  name: core-tests
it's not `core` anymore, and all other configmaps have the `-overrides` suffix, so I'd suggest to rename it to `console-overrides`

2020-09-07 17:27 UTC, Wawrzyn321 commented
/retest

2020-09-08 05:16 UTC, dariadomagala approved these changes

2020-09-08 07:35 UTC, aerfio approved these changes

2020-09-08 07:36 UTC, merged