Add buildResources field in Function model in cbs
kyma-project/kyma pull request #9447
Opened 2020-09-14 13:42 UTC by magicmatatjahu

**Description**

Changes proposed in this pull request:

As in title: Add buildResources field in Function model in cbs.

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9227

2020-09-14 13:53 UTC, magicmatatjahu commented
/test pre-kyma-components-console-backend-service

2020-09-16 17:14 UTC, magicmatatjahu commented
/test pre-kyma-components-console-backend-service

2020-09-25 11:13 UTC, magicmatatjahu commented
/test pre-kyma-components-console-backend-service

2020-09-25 12:18 UTC, aerfio requested changes

2020-09-27 14:28 UTC, magicmatatjahu commented on components/console-backend-service/go.mod
> +	k8s.io/utils => k8s.io/utils v0.0.0-20191114184206-e782cd3c129f+incompatible
`k8s.io/utils` versions from 2020* year (btw. it was fetched via changes to function-controller) has one of standard libs (as I remember `time`) of go in `1.13` version and cbs is in `1.12`, so in compilation time of tests I had an errors - only in tests.

2020-09-28 11:17 UTC, aerfio approved these changes

2020-10-12 09:11 UTC, magicmatatjahu commented
/test all

2020-10-12 09:43 UTC, Wawrzyn321 approved these changes

2020-10-12 15:00 UTC, merged