Release 1.16.0 rc1
kyma-project/kyma pull request #9449
Opened 2020-09-14 14:12 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2020-09-14 14:19 UTC, dbadura commented
/test pre-rel116-kyma-integration

2020-09-14 14:31 UTC, dbadura commented
/test pre-rel116-kyma-installer

2020-09-14 14:44 UTC, dbadura commented
/test pre-rel116-kyma-installer

2020-09-14 14:47 UTC, dbadura commented
/test pre-rel116-kyma-artifacts

2020-09-14 14:55 UTC, dbadura commented
/test pre-rel116-kyma-integration

2020-09-14 15:35 UTC, dbadura commented
/test pre-rel116-kyma-installer

2020-09-14 15:36 UTC, dbadura commented
/test pre-rel116-kyma-artifacts

2020-09-14 15:39 UTC, dbadura commented
/test pre-rel116-kyma-gke-central-connector

2020-09-14 15:39 UTC, dbadura commented
/test pre-rel116-kyma-gke-compass-integration

2020-09-14 15:39 UTC, dbadura commented
/test pre-rel116-kyma-gke-integration

2020-09-14 15:39 UTC, dbadura commented
/test pre-rel116-kyma-gke-upgrade

2020-09-15 05:44 UTC, dbadura commented
/retest

2020-09-15 06:07 UTC, dariadomagala requested changes

2020-09-15 06:07 UTC, dariadomagala commented on resources/core/values.yaml
> +    clusterAssetGroupsVersion: release-1.16.0-rc1
here it's enough to have the "main" release version
```suggestion
    clusterAssetGroupsVersion: release-1.16
```

2020-09-15 06:09 UTC, dbadura commented
/test pre-rel116-kyma-integration

2020-09-15 06:13 UTC, dariadomagala approved these changes

2020-09-15 06:47 UTC, magicmatatjahu approved these changes

2020-09-15 06:48 UTC, strekm approved these changes
/meow

2020-09-15 06:53 UTC, dbadura commented
/test pre-rel116-kyma-installer

2020-09-15 06:54 UTC, dbadura commented
/test pre-rel116-kyma-artifacts

2020-09-15 06:57 UTC, dbadura commented
/test pre-rel116-kyma-gke-central-connector
/test pre-rel116-kyma-gke-compass-integration
/test pre-rel116-kyma-gke-integration
/test pre-rel116-kyma-gke-upgrade

2020-09-15 08:13 UTC, m00g3n approved these changes

2020-09-15 08:18 UTC, merged