Disable testing targets if they are healthy or not
kyma-project/kyma pull request #9514
Opened 2020-09-23 15:27 UTC by rakesh-garimella

**Description**

Changes proposed in this pull request:

- Currenetly we are dropping the namespace and pod labels from pod monitors so we cannot ignore them anymore. So dont test targets as of now. Check it manually

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/8898

2020-09-23 15:31 UTC, a-thaler submitted a review, later dismissed

2020-09-24 07:49 UTC, k15r requested changes

2020-09-24 07:49 UTC, k15r commented on tests/end-to-end/upgrade/pkg/tests/monitoring/targets_rules.go
> +	// log.Println("checking that all targets are healthy before upgrade")
dead code, please remove

2020-09-24 08:42 UTC, k15r approved these changes

2020-09-24 08:44 UTC, hisarbalik approved these changes

2020-09-24 08:44 UTC, merged