add error callback
kyma-project/kyma pull request #9580
Opened 2020-09-29 13:07 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2020-10-16 07:55 UTC, tgorgol commented
Remember to remove the additional logs after cleanup and I think it would be better to log a single resource only once (for example only for create operations, because the logs are cluttered otherwise).

2020-10-16 14:44 UTC, dbadura commented
/retest

2020-10-19 14:06 UTC, dbadura commented
/retest

2020-10-20 10:00 UTC, aerfio requested changes
I'll have to check how those logs look like, but it mostly looks ok 💪 

extract that json.MarshallIndent to some kind of function and take care of those TODO's that you've added, as well as commented out code

2020-10-20 12:24 UTC, dbadura commented on tests/function-controller/testsuite/teststep/gitrepository.go
> +	return nil
I can fetch the code from git repository

2020-10-20 12:25 UTC, dbadura commented on tests/function-controller/testsuite/teststep/check.go
> +	return nil
No it's not needed, because this step only do some HTTP requets.

2020-10-20 13:56 UTC, dbadura commented on tests/function-controller/Makefile
> +include $(SCRIPTS_DIR)/generic-make-go.mk
I want to include the `generic makefile` to check if source code is properly formated and run unit test.

2020-10-20 13:56 UTC, dbadura commented on tests/function-controller/pkg/addons/addons.go
> +	out, err := json.MarshalIndent(ad, "", "  ")
Good idea

2020-10-20 13:57 UTC, dbadura commented on tests/function-controller/pkg/step/parallel_test.go
> +package step_test
Yes, those tests are executed because those test check if paralel/serial executor works as needed.

2020-10-20 14:00 UTC, dbadura commented on tests/function-controller/pkg/step/serial.go
> +//TODO: Write test if steps are correclty executed and OnError also
Yes, it's leftover. It 's tested in: https://github.com/kyma-project/kyma/pull/9580/files#diff-6323a441170ea12575de7aab4d9aa115a699132f8e26a2697f9916183e88345cR13-R43

2020-10-20 14:00 UTC, dbadura commented on tests/function-controller/pkg/step/step.go
> +	//var startedStep int
Remove this code

2020-10-20 14:01 UTC, dbadura commented on tests/function-controller/pkg/step/step.go
> +// Cleanup cleans up given Steps in reverse order
revert

2020-10-20 14:01 UTC, dbadura commented on tests/function-controller/testsuite/teststep/commitchanges.go
> +	return nil
I can fetch the code from repository

2020-10-23 11:29 UTC, dbadura commented
/test pre-master-kyma-gke-compass-integration

2020-10-26 07:05 UTC, dbadura commented
/retest

2020-10-26 12:47 UTC, aerfio approved these changes

2020-10-26 12:47 UTC, merged