Add TargetKind reconciler
kyma-project/kyma pull request #9802
Opened 2020-10-30 08:16 UTC by ksputo

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2020-11-03 11:20 UTC, polskikiel requested changes

2020-11-03 11:20 UTC, polskikiel commented on components/binding/internal/controller/targetkind_reconciler.go
> +		r.log.Warnf("TargetKind %s not found during reconcile process: %s", req.NamespacedName, err)
why we don't return error here? Are you sure it's not found error?

2020-11-03 11:20 UTC, polskikiel commented on components/binding/internal/storage/storage.go
> +		return &ResourceData{}, errors.New(fmt.Sprintf("TargetKind %s was not found", kind))
it's better to use `Errorf` - btw. can we return here a typed error?

2020-11-03 11:20 UTC, polskikiel commented on components/binding/internal/worker/targetkind.go
> +
unnecessary whitespace

2020-11-03 11:37 UTC, jasiu001 commented
make `go fmt` for all files

2020-11-03 14:37 UTC, jasiu001 requested changes

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +func (w *TargetKindWorker) reconcileUponDelete(targetKind v1alpha1.TargetKind) error {
unused method

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +func (w *TargetKindWorker) reconcileUponAddUpdate(targetKind v1alpha1.TargetKind) error {
Must this be a separate method?

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +	// create client for kind and save to storage
I think the comment is out of date :)

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +	_, err := w.storage.Get(storage.Kind(targetKind.Name))
IMO is better to make a field `targetKind.Name` as `Kind` type inside `/pkg/apis/v1alpha1/targetkind_types.go` then you don't have to map all the time

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +func (w *TargetKindWorker) Process(targetKind *v1alpha1.TargetKind, log log.FieldLogger) (*v1alpha1.TargetKind, error) {
you use the same block of code twice, maybe easier will be:
```go
	if targetKind.Status.Registered {
		if w.storage.Is(targetKind.Name) {
			log.Infof("TargetKind %q was already registered", targetKind.Name)
			return targetKind, nil
		}
	}
	err := w.reconcileUponAddUpdate(*targetKind)
	if err != nil {
		return &v1alpha1.TargetKind{}, errors.New(fmt.Sprintf("while registering TargetKind %q", targetKind.Spec.DisplayName))
	}
	targetKind.Status.Registered = true
	log.Infof("TargetKind %q registered", targetKind.Name)
	return targetKind, nil
```

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
>  // TODO: change Handler methods when TargetKind logic will be ready
remove TODO, you made this already :)

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +		return nil, errors.Wrap(err, "while getting resource")
maybe as a temporary?

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +		return make(map[string]string, 0), err
wrap all errors if has sense

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +		strKey := fmt.Sprintf("%v", key)
what is the reason to make this `fmt.Sprintf("%v", key)`?

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +	for key, _ := range resourceLabels {
you can ommit:
```go
for key := range resourceLabels {
...
```

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> -			deployment.Spec.Template.ObjectMeta.Labels[h.labelKey(b)] = uuid.New().String()
I don't understand this part: you fetch all labels, then iterate for keys, and if a label exists you `ensureLabelsAreApplied` ?

2020-11-03 14:37 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +		labelsToDelete[key] = value
IMO it has no sense, the only label in `labelsToDelete` for this concrete Binding will be: `h.labelKey(b)`
and value is not necessary, if I am correct you not use value inside `ensureLabelsAreDeleted()` method

2020-11-04 08:55 UTC, polskikiel approved these changes
lgtm

2020-11-05 07:20 UTC, jasiu001 requested changes

2020-11-05 07:20 UTC, jasiu001 commented on components/binding/pkg/apis/v1alpha1/binding_types.go
> +	Kind Kind `json:"kind"`
leave string here

2020-11-05 07:20 UTC, jasiu001 commented on components/binding/pkg/apis/v1alpha1/targetkind_types.go
> +	Kind    Kind `json:"kind"`
make `go fmt` for all files

2020-11-05 07:20 UTC, jasiu001 commented on components/binding/internal/worker/targetkind.go
> +		return &v1alpha1.TargetKind{}, errors.New(fmt.Sprintf("while registering TargetKind %q", targetKind.Spec.DisplayName))
return `targetKind` not `&v1alpha1.TargetKind{}`

2020-11-05 07:20 UTC, jasiu001 commented on components/binding/internal/storage/storage.go
> +	return exists
check if `LabelsPath` is the same

2020-11-05 07:20 UTC, jasiu001 commented on components/binding/internal/target/handler.go
> +	logrus.Infof("Got resource: %+v", resource)
remove single logrus

2020-11-05 13:38 UTC, jasiu001 approved these changes

2020-11-05 13:43 UTC, merged